import { describe, expect, it } from "vitest";
import { AgentOrchestrator } from "../src/agent.js";
import { ResultAwareToolModelProvider, ScriptedToolModelProvider } from "../src/agent-mocks.js";
import { MockToolProvider } from "../src/tool-mocks.js";
import { ToolRouter } from "../src/tools.js";
import { ToolContext } from "../src/index.js";
const context = (signal = new AbortController().signal, deadline?: number): ToolContext => ({ traceId: "trace", sessionId: "session", executionId: "agent", signal, deadline });
async function collect<T>(source: AsyncIterable<T>): Promise<T[]> { const result: T[] = []; for await (const value of source) result.push(value); return result; }
async function router() { const tools = new ToolRouter(); await tools.register("provider", new MockToolProvider("provider"), context()); return tools; }
describe("AgentExecution", () => {
  it("completes text-only execution", async () => { const execution = new AgentOrchestrator(new ScriptedToolModelProvider([[{ type: "text", text: "hello" }]])).create("input", context()); const events = await collect(execution.events()); expect((await execution.result()).status).toBe("completed"); expect(events.map((event) => event.type)).toEqual(["started", "model-started", "model-text", "completed"]); });
  it("performs a tool round trip and correlates result", async () => { const tools = await router(); const model = new ResultAwareToolModelProvider(); const execution = new AgentOrchestrator(model, tools).create("input", context(), tools.listTools()); const events = await collect(execution.events()); expect((await execution.result()).text).toBe("sum accepted"); expect(events.map((event) => event.type)).toEqual(["started", "model-started", "tool-requested", "tool-started", "tool-completed", "model-started", "model-text", "completed"]); expect(model.turns).toBe(2); });
  it("supports multiple calls sequentially", async () => { const tools = await router(); const model = new ScriptedToolModelProvider([[{ type: "tool", toolId: "provider/echo", input: { value: "a" }, id: "a" }, { type: "tool", toolId: "provider/add", input: { left: 1, right: 2 }, id: "b" }], [{ type: "text", text: "done" }]]); const execution = new AgentOrchestrator(model, tools).create("input", context(), tools.listTools()); const events = await collect(execution.events()); expect((await execution.result()).status).toBe("completed"); expect(events.filter((event) => event.type === "tool-completed")).toHaveLength(2); });
  it("feeds controlled tool failures back to the model", async () => { const tools = await router(); const model = new ScriptedToolModelProvider([[{ type: "tool", toolId: "provider/missing", input: {}, id: "missing" }], [{ type: "text", text: "recovered" }]]); const execution = new AgentOrchestrator(model, tools).create("input", context(), tools.listTools()); expect((await execution.result()).text).toBe("recovered"); });
  it("rejects duplicate calls and enforces limits", async () => { const tools = await router(); const duplicate = new ScriptedToolModelProvider([[{ type: "tool", toolId: "provider/echo", input: { value: 1 }, id: "same" }, { type: "tool", toolId: "provider/echo", input: { value: 2 }, id: "same" }]]); expect((await new AgentOrchestrator(duplicate, tools).create("input", context(), tools.listTools()).result()).status).toBe("failed"); const limited = new ScriptedToolModelProvider([[{ type: "tool", toolId: "provider/echo", input: {}, id: "one" }], [{ type: "text", text: "never" }]]); expect((await new AgentOrchestrator(limited, tools, { maxSteps: 1, maxToolCalls: 5 }).create("input", context(), tools.listTools()).result()).status).toBe("limit-reached"); });
  it("cancels during model and tool", async () => { const controller = new AbortController(); const execution = new AgentOrchestrator(new ScriptedToolModelProvider([[{ type: "text", text: "x" }]])).create("input", context(controller.signal)); controller.abort(); expect((await execution.result()).status).toBe("cancelled"); const tools = await router(); const active = new AgentOrchestrator(new ScriptedToolModelProvider([[{ type: "tool", toolId: "provider/slow", input: {}, id: "slow" }]]), tools).create("input", context(), tools.listTools()); await new Promise((resolve) => setTimeout(resolve, 0)); const events = active.events(); await events[Symbol.asyncIterator]().next(); await active.cancel(); expect((await active.result()).status).toBe("cancelled"); });
  it("enforces global deadline", async () => { const tools = await router(); const execution = new AgentOrchestrator(new ScriptedToolModelProvider([[{ type: "tool", toolId: "provider/slow", input: {}, id: "slow" }]]), tools).create("input", context(new AbortController().signal, Date.now() + 2), tools.listTools()); expect((await execution.result()).status).toBe("timed-out"); });
});
