import { describe, expect, it } from "vitest";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { AgentOrchestrator } from "../src/agent.js";
import { ScriptedToolModelProvider } from "../src/agent-mocks.js";
import { StaticApprovalProvider, StaticToolAuthorizationPolicy } from "../src/authorization-mocks.js";
import { MCPToolProvider } from "../src/adapters/tool-mcp.js";
import { JsonValue, ToolAuthorizationRequest, ToolContext, ToolRouter } from "../src/index.js";
import { MockToolProvider } from "../src/tool-mocks.js";

const context = (signal = new AbortController().signal, deadline?: number): ToolContext => ({ traceId: "trace", sessionId: "session", executionId: "qualification", signal, deadline });
const call = (id = "call-1", toolId = "provider/echo", input: JsonValue = { value: "qualification" }) => [{ type: "tool" as const, id, toolId, input }];
async function setup(provider = new MockToolProvider("provider")) { const tools = new ToolRouter(); await tools.register("provider", provider, context()); return { tools, provider }; }
async function execute(tools: ToolRouter, policy: { authorize(request: ToolAuthorizationRequest): Promise<"allow" | "deny" | "require-approval"> }, approvalProvider?: { approve(request: import("../src/index.js").ToolApprovalRequest): Promise<{ approved: boolean; reason?: string }> }, deadline?: number) { const model = new ScriptedToolModelProvider([call(), [{ type: "text", text: "handled" }]]); const execution = new AgentOrchestrator(model, tools, undefined, { policy, approvalProvider }).create("qualify", context(new AbortController().signal, deadline), tools.listTools()); return { model, execution }; }

describe("authorization qualification", () => {
  it("qualifies allow, deny, approval, missing approval, and infrastructure failures", async () => {
    const allowed = await setup(); const allowPolicy = new StaticToolAuthorizationPolicy("allow"); const allow = await execute(allowed.tools, allowPolicy); expect((await allow.execution.result()).status).toBe("completed"); expect(allowed.provider.calls).toHaveLength(1);
    const denied = await setup(); const deny = await execute(denied.tools, new StaticToolAuthorizationPolicy("deny")); expect((await deny.execution.result()).status).toBe("completed"); expect(denied.provider.calls).toHaveLength(0); expect(deny.model.received[1]?.messages?.at(-1)).toMatchObject({ role: "tool", result: { error: { code: "AUTHORIZATION_DENIED" } } });
    const approved = await setup(); const approval = new StaticApprovalProvider(true); const approvedRun = await execute(approved.tools, new StaticToolAuthorizationPolicy("require-approval"), approval); expect((await approvedRun.execution.result()).status).toBe("completed"); expect(approved.provider.calls).toHaveLength(1); expect(approval.requests).toHaveLength(1);
    const missing = await setup(); const missingRun = await execute(missing.tools, new StaticToolAuthorizationPolicy("require-approval")); expect((await missingRun.execution.result()).status).toBe("completed"); expect(missing.provider.calls).toHaveLength(0);
    const policyCalls: ToolAuthorizationRequest[] = []; const policyFailure = await setup(); const throwingPolicy = { authorize: async (request: ToolAuthorizationRequest) => { policyCalls.push(request); throw new Error("policy unavailable"); } }; const failedPolicy = await execute(policyFailure.tools, throwingPolicy); expect((await failedPolicy.execution.result()).status).toBe("completed"); expect(policyCalls).toHaveLength(1); expect(policyFailure.provider.calls).toHaveLength(0);
    const approvalCalls: unknown[] = []; const approvalFailure = await setup(); const throwingApproval = { approve: async (request: import("../src/index.js").ToolApprovalRequest) => { approvalCalls.push(request); throw new Error("approval unavailable"); } }; const failedApproval = await execute(approvalFailure.tools, new StaticToolAuthorizationPolicy("require-approval"), throwingApproval); expect((await failedApproval.execution.result()).status).toBe("completed"); expect(approvalCalls).toHaveLength(1); expect(approvalFailure.provider.calls).toHaveLength(0);
  });

  it("is cancellation and deadline safe while policy or approval is pending", async () => {
    let releasePolicy!: () => void; let policyCalls = 0; const pendingPolicy = { authorize: async () => { policyCalls++; return new Promise<"allow">((resolve) => { releasePolicy = () => resolve("allow"); }); } }; const policySetup = await setup(); const policyRun = await execute(policySetup.tools, pendingPolicy); await new Promise((resolve) => setTimeout(resolve, 0)); await policyRun.execution.cancel(); expect((await policyRun.execution.result()).status).toBe("cancelled"); expect(policyCalls).toBe(1); expect(policySetup.provider.calls).toHaveLength(0); releasePolicy();
    let releaseApproval!: () => void; let approvalCalls = 0; const pendingApproval = { approve: async () => { approvalCalls++; return new Promise<{ approved: boolean }>((resolve) => { releaseApproval = () => resolve({ approved: true }); }); } }; const approvalSetup = await setup(); const approvalRun = await execute(approvalSetup.tools, new StaticToolAuthorizationPolicy("require-approval"), pendingApproval); await new Promise((resolve) => setTimeout(resolve, 0)); await approvalRun.execution.cancel(); expect((await approvalRun.execution.result()).status).toBe("cancelled"); expect(approvalCalls).toBe(1); expect(approvalSetup.provider.calls).toHaveLength(0); releaseApproval();
    let releaseDeadlinePolicy!: () => void; const deadlinePolicy = { authorize: async () => new Promise<"allow">((resolve) => { releaseDeadlinePolicy = () => resolve("allow"); }) }; const deadlinePolicySetup = await setup(); const deadlinePolicyRun = await execute(deadlinePolicySetup.tools, deadlinePolicy, undefined, Date.now() + 5); expect((await deadlinePolicyRun.execution.result()).status).toBe("timed-out"); expect(deadlinePolicySetup.provider.calls).toHaveLength(0); releaseDeadlinePolicy();
    let releaseDeadlineApproval!: () => void; const deadlineApproval = { approve: async () => new Promise<{ approved: boolean }>((resolve) => { releaseDeadlineApproval = () => resolve({ approved: true }); }) }; const deadlineApprovalSetup = await setup(); const deadlineApprovalRun = await execute(deadlineApprovalSetup.tools, new StaticToolAuthorizationPolicy("require-approval"), deadlineApproval, Date.now() + 5); expect((await deadlineApprovalRun.execution.result()).status).toBe("timed-out"); expect(deadlineApprovalSetup.provider.calls).toHaveLength(0); releaseDeadlineApproval();
  });

  it("preserves identity, input, descriptors, provider scope, and duplicate protection", async () => {
    const { tools, provider } = await setup(); const input = { path: "/tmp/example", options: { mode: "safe" } }; const authorization: ToolAuthorizationRequest[] = []; const approvals = new StaticApprovalProvider(true); const policy = { authorize: async (request: ToolAuthorizationRequest) => { authorization.push(request); return "require-approval" as const; } }; const model = new ScriptedToolModelProvider([call("call-1", "provider/echo", input), [{ type: "tool", id: "call-1", toolId: "provider/echo", input }, { type: "text", text: "duplicate" }]]); const execution = new AgentOrchestrator(model, tools, undefined, { policy, approvalProvider: approvals }).create("qualify", context(), tools.listTools()); expect((await execution.result()).status).toBe("failed"); expect(authorization).toHaveLength(1); expect(approvals.requests).toHaveLength(1); expect(provider.calls).toHaveLength(1); expect(authorization[0]?.invocation.toolId).toBe("provider/echo"); expect(authorization[0]?.invocation.input).toEqual(input); expect(approvals.requests[0]?.invocation.input).toEqual(input);
    const unknown = await setup(); let unknownAuth = 0; const unknownModel = new ScriptedToolModelProvider([[{ type: "tool", id: "missing", toolId: "provider/missing", input: {} }], [{ type: "text", text: "unknown handled" }]]); const unknownExecution = new AgentOrchestrator(unknownModel, unknown.tools, undefined, { policy: { authorize: async () => { unknownAuth++; return "allow"; } } }).create("qualify", context(), unknown.tools.listTools()); expect((await unknownExecution.result()).status).toBe("completed"); expect(unknownAuth).toBe(0); expect(unknown.provider.calls).toHaveLength(0);
    const scopedTools = new ToolRouter(); await scopedTools.register("server-a", new MockToolProvider("server-a"), context()); await scopedTools.register("server-b", new MockToolProvider("server-b"), context()); const ids: string[] = []; const scopedPolicy = { authorize: async (request: ToolAuthorizationRequest) => { ids.push(request.invocation.toolId); return "deny" as const; } }; const scopedModel = new ScriptedToolModelProvider([[{ type: "tool", id: "a", toolId: "server-a/echo", input: { value: 1 } }, { type: "tool", id: "b", toolId: "server-b/echo", input: { value: 2 } }], [{ type: "text", text: "done" }]]); const scopedExecution = new AgentOrchestrator(scopedModel, scopedTools, undefined, { policy: scopedPolicy }).create("qualify", context(), scopedTools.listTools()); await scopedExecution.result(); expect(ids).toEqual(["server-a/echo", "server-b/echo"]);
  });

  it("composes approval with real MCP stdio exactly once and blocks denial", async () => {
    const directory = mkdtempSync(join(tmpdir(), "harness-mcp-")); const countFile = join(directory, "calls"); const script = new URL("../dist/tests/mcp-fixture-server.js", import.meta.url).pathname; const provider = new MCPToolProvider({ providerId: "fixture", command: process.execPath, args: [script], env: { ...process.env, MCP_CALL_COUNT_FILE: countFile } }); const router = new ToolRouter();
    try { await router.register("fixture", provider, context()); const approvals = new StaticApprovalProvider(true); const approvedModel = new ScriptedToolModelProvider([[{ type: "tool", id: "mcp-approve", toolId: "fixture/echo", input: { value: "mcp-approved" } }], [{ type: "text", text: "mcp complete" }]]); const approvedExecution = new AgentOrchestrator(approvedModel, router, undefined, { policy: new StaticToolAuthorizationPolicy("require-approval"), approvalProvider: approvals }).create("qualify", context(), router.listTools()); expect((await approvedExecution.result()).status).toBe("completed"); expect(approvals.requests).toHaveLength(1); expect(readFileSync(countFile, "utf8").trim().split("\n")).toHaveLength(1);
      const deniedApprovals = new StaticApprovalProvider(false); const deniedModel = new ScriptedToolModelProvider([[{ type: "tool", id: "mcp-deny", toolId: "fixture/echo", input: { value: "mcp-denied" } }], [{ type: "text", text: "denial handled" }]]); const deniedExecution = new AgentOrchestrator(deniedModel, router, undefined, { policy: new StaticToolAuthorizationPolicy("require-approval"), approvalProvider: deniedApprovals }).create("qualify", context(), router.listTools()); expect((await deniedExecution.result()).status).toBe("completed"); expect(deniedApprovals.requests).toHaveLength(1); expect(readFileSync(countFile, "utf8").trim().split("\n")).toHaveLength(1);
    } finally { await provider.close(); rmSync(directory, { recursive: true, force: true }); }
  });
});
