import { describe, expect, it } from "vitest";
import { DenoProcess, DenoRuntime, buildDenoArguments, denoRuntimeConfigSchema } from "../src/adapters/runtime-deno.js";
import { DenoPermissionSandbox, denoPermissionBindingKind, denoPermissionPayloadSchema, mapExecutionPolicyToDenoPermissions } from "../src/adapters/sandbox-deno-permissions.js";
import { ExecutionRequest, RuntimeEvent } from "../src/index.js";
import { RuntimeCoordinator } from "../src/runtime.js";

class FakeProcess implements DenoProcess { readonly stdin = { end: (data?: string) => { this.input = data; } }; input?: string; killed = false; constructor(readonly stdout: AsyncIterable<Buffer>, readonly stderr: AsyncIterable<Buffer>, readonly exited: Promise<{ code: number | null; signal?: string | null }>, private readonly terminate: () => void = () => {}) {} kill() { this.killed = true; this.terminate(); } }
const request = (language: "javascript" | "typescript" = "javascript"): ExecutionRequest => ({ schemaVersion: 1, language, source: "console.log('ok')", policy: { filesystem: "deny", network: "deny", codeLoading: "allow" } });
const context = (signal = new AbortController().signal, deadline?: number) => ({ traceId: "trace", sessionId: "session", executionId: "execution", signal, deadline });
async function* chunks(...values: string[]) { for (const value of values) yield Buffer.from(value); }
async function collect(source: AsyncIterable<RuntimeEvent>): Promise<RuntimeEvent[]> { const result: RuntimeEvent[] = []; for await (const event of source) result.push(event); return result; }

describe("Deno adapters", () => {
  it("maps policy to a truthful binding", async () => { expect(denoRuntimeConfigSchema.parse({ executable: "deno" })).toEqual({ executable: "deno" }); expect(mapExecutionPolicyToDenoPermissions({ filesystem: "deny", network: "allow", codeLoading: "deny" })).toEqual({ filesystem: "deny", network: "allow" }); const session = await new DenoPermissionSandbox().create(request().policy); expect(session.binding).toMatchObject({ schemaVersion: 1, kind: denoPermissionBindingKind, payload: { filesystem: "deny", network: "deny" } }); expect(denoPermissionPayloadSchema.parse(session.binding!.payload)).toBeTruthy(); });
  it("constructs restrictive language-specific argv", () => { const js = buildDenoArguments(request("javascript"), { filesystem: "deny", network: "deny" }); const ts = buildDenoArguments(request("typescript"), { filesystem: "allow", network: "allow" }); expect(js).toContain("--ext=js"); expect(ts).toContain("--ext=ts"); expect(ts).toContain("--allow-read"); expect(ts).toContain("--allow-write"); expect(ts).toContain("--allow-net"); expect(ts).not.toContain("-A"); expect(ts).not.toContain("--allow-all"); expect(ts).toContain("--no-prompt"); });
  it("streams stdout/stderr and preserves completion", async () => { let finish!: (value: { code: number | null }) => void; const process = new FakeProcess(chunks("out"), chunks("err"), new Promise((resolve) => { finish = resolve; })); const runtime = new DenoRuntime({}, () => process); const session = await new DenoPermissionSandbox().create(request().policy); const execution = await runtime.createExecution(request(), context(), session); finish({ code: 0 }); expect((await collect(execution.events())).map((event) => event.type)).toEqual(["started", "stdout", "stderr", "exited", "completed"]); expect(process.input).toBe(request().source); });
  it("rejects malformed/unsupported bindings and spawn failures", async () => { const runtime = new DenoRuntime({}, () => { throw new Error("missing"); }); const session = await new DenoPermissionSandbox().create(request().policy); await expect(runtime.createExecution(request(), context(), session)).rejects.toMatchObject({ error: { code: "RUNTIME_FAILED" } }); await expect(runtime.createExecution(request(), context(), { id: "none", dispose: async () => {} })).rejects.toMatchObject({ error: { code: "POLICY_VIOLATION" } }); });
  it("preserves cancellation and deadline terminal causes", async () => { let finish!: (value: { code: number | null; signal: string }) => void; const process = new FakeProcess(chunks(), chunks(), new Promise((resolve) => { finish = resolve; }), () => finish({ code: null, signal: "SIGTERM" })); const runtime = new DenoRuntime({}, () => process); const session = await new DenoPermissionSandbox().create(request().policy); const execution = await runtime.createExecution(request(), context(), session); const iterator = execution.events()[Symbol.asyncIterator](); await iterator.next(); await execution.cancel(); expect(process.killed).toBe(true); expect((await execution.result()).status).toBe("cancelled"); });
  it("reports health without executing source", async () => { const process = new FakeProcess(chunks("deno 2.9.4\n"), chunks(), Promise.resolve({ code: 0 })); expect(await new DenoRuntime({}, () => process).health()).toEqual({ status: "healthy" }); expect((await new DenoRuntime({}, () => { throw new Error("missing"); }).health()).reason).toBe("resource-unavailable"); });
});

const live = process.env.RUN_DENO_INTEGRATION_TESTS === "1" ? describe : describe.skip;
live("Deno live qualification", () => {
  it("runs JavaScript and TypeScript", async () => { const runtime = new DenoRuntime({ executable: process.env.DENO_BIN }); const coordinator = new RuntimeCoordinator(runtime, new DenoPermissionSandbox()); for (const item of [{ language: "javascript" as const, source: "console.log('DENO_JS_OK')" }, { language: "typescript" as const, source: "const value: number = 42; console.log(value)" }]) { const execution = await coordinator.createExecution({ schemaVersion: 1, ...item, policy: { filesystem: "deny", network: "deny", codeLoading: "allow" } }, { ...context(), deadline: Date.now() + 10000 }); const events = await collect(execution.events()); expect(events.some((event) => event.type === "stdout")).toBe(true); expect((await execution.result()).status).toBe("completed"); } });
  it("qualifies filesystem and network direct access", async () => { const fs = await import("node:fs/promises"); const directory = await fs.mkdtemp("/tmp/harness-deno-"); const target = `${directory}/target.txt`; const runtime = new DenoRuntime({ executable: process.env.DENO_BIN }); const run = async (policy: ExecutionRequest["policy"], source: string) => { const execution = await new RuntimeCoordinator(runtime, new DenoPermissionSandbox()).createExecution({ schemaVersion: 1, language: "typescript", source, policy }, { ...context(), deadline: Date.now() + 10000 }); await collect(execution.events()); return execution.result(); }; try { expect((await run({ filesystem: "deny", network: "deny", codeLoading: "allow" }, `await Deno.writeTextFile(${JSON.stringify(target)}, 'DENIED')`)).status).toBe("failed"); expect((await run({ filesystem: "allow", network: "deny", codeLoading: "allow" }, `await Deno.writeTextFile(${JSON.stringify(target)}, 'ALLOWED')`)).status).toBe("completed"); } finally { await fs.rm(directory, { recursive: true, force: true }); } });
  it("separates stderr and maps controlled failure", async () => { const runtime = new DenoRuntime({ executable: process.env.DENO_BIN }); const execution = await new RuntimeCoordinator(runtime, new DenoPermissionSandbox()).createExecution({ schemaVersion: 1, language: "typescript", source: "console.error('DENO_STDERR_OK'); throw new Error('DENO_FAILURE')", policy: { filesystem: "deny", network: "deny", codeLoading: "allow" } }, { ...context(), deadline: Date.now() + 10000 }); const events = await collect(execution.events()); expect(events.some((event) => event.type === "stderr" && event.data.includes("DENO_STDERR_OK"))).toBe(true); expect((await execution.result()).status).toBe("failed"); });
  it("preserves cancellation and deadline terminal causes", async () => { const runtime = new DenoRuntime({ executable: process.env.DENO_BIN }); const create = (deadline: number) => new RuntimeCoordinator(runtime, new DenoPermissionSandbox()).createExecution({ schemaVersion: 1, language: "typescript", source: "setInterval(() => {}, 1000)", policy: { filesystem: "deny", network: "deny", codeLoading: "allow" } }, { ...context(), deadline }); const cancelled = await create(Date.now() + 10000); const iterator = cancelled.events()[Symbol.asyncIterator](); await iterator.next(); await cancelled.cancel(); expect((await cancelled.result()).status).toBe("cancelled"); const timed = await create(Date.now() + 20); expect((await timed.result()).status).toBe("timed-out"); });
  it("qualifies network denial and allowance against a local server", async () => { const { createServer } = await import("node:http"); const server = createServer((_request, response) => response.end("NETWORK_OK")); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); const address = server.address(); if (!address || typeof address === "string") throw new Error("server address unavailable"); const runtime = new DenoRuntime({ executable: process.env.DENO_BIN }); const source = `const response = await fetch(${JSON.stringify(`http://127.0.0.1:${address.port}/`)}); console.log(await response.text())`; const run = async (network: "allow" | "deny") => { const execution = await new RuntimeCoordinator(runtime, new DenoPermissionSandbox()).createExecution({ schemaVersion: 1, language: "typescript", source, policy: { filesystem: "deny", network, codeLoading: "allow" } }, { ...context(), deadline: Date.now() + 10000 }); await collect(execution.events()); return execution.result(); }; try { expect((await run("deny")).status).toBe("failed"); expect((await run("allow")).status).toBe("completed"); } finally { await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); } });
  it("characterizes static local imports separately from filesystem policy", async () => { const fs = await import("node:fs/promises"); const directory = await fs.mkdtemp("/tmp/harness-deno-import-"); const modulePath = `${directory}/module.ts`; await fs.writeFile(modulePath, "export const value = 'LOCAL_IMPORT_OK';"); try { const runtime = new DenoRuntime({ executable: process.env.DENO_BIN }); const execution = await new RuntimeCoordinator(runtime, new DenoPermissionSandbox()).createExecution({ schemaVersion: 1, language: "typescript", source: `import { value } from ${JSON.stringify(modulePath)}; console.log(value)`, policy: { filesystem: "deny", network: "deny", codeLoading: "allow" } }, { ...context(), deadline: Date.now() + 10000 }); const events = await collect(execution.events()); expect((await execution.result()).status).toBe("completed"); expect(events.some((event) => event.type === "stdout" && event.data.includes("LOCAL_IMPORT_OK"))).toBe(true); } finally { await fs.rm(directory, { recursive: true, force: true }); } });
  it("rejects hard code-loading denial before Deno starts", async () => { const runtime = new DenoRuntime({ executable: process.env.DENO_BIN }); const sandbox = new DenoPermissionSandbox(); await expect(new RuntimeCoordinator(runtime, sandbox).createExecution({ schemaVersion: 1, language: "typescript", source: "console.log('not-started')", policy: { filesystem: "deny", network: "deny", codeLoading: "deny" } }, { ...context(), deadline: Date.now() + 10000 })).rejects.toMatchObject({ error: { code: "POLICY_VIOLATION" } }); });
});
