import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createPortaApplication } from "../src/porta-application.js";
import { parsePortaConfig } from "../src/porta-config.js";
import { ModelContext, ModelEvent, ModelMessage, ModelProvider, ModelRequest, ModelToolCall, ToolContext } from "../src/contracts.js";
import { HostProcessRuntime } from "../src/adapters/runtime-host-process.js";
import { HostProcessSandbox } from "../src/adapters/sandbox-host-process.js";
import { DeterministicConversationCompactor } from "../src/compaction.js";

class QualificationModel implements ModelProvider {
  readonly descriptor = { id: "qualification-model", version: "1", capabilities: [{ id: "model.tools", version: "1" }] };
  readonly requests: ModelRequest[] = []; readonly executionExitCodes: number[] = []; completionRejected = 0; artifactHydrated = false; private nextId = 0; private version = 1;
  constructor(private readonly actions: readonly string[], private readonly expectedHash = "2576daf7db87f44ffa15dc1a314a61bb8d55a75308343682e404e951c4a83f5f") {}
  async *generate(request: ModelRequest, _context: ModelContext): AsyncIterable<ModelEvent> { this.requests.push(request); const action = (this.actions as string[]).shift(); if (!action || action === "text") { yield { type: "delta", text: "continuing qualification" }; yield { type: "completed" }; return; } const [toolId, parameter] = action.split("|", 2); const input = this.input(toolId!, parameter, request); const canonicalToolId = ["task/add-criterion", "task/add-step", "task/activate", "task/evidence", "task/evidence-fail", "task/complete"].includes(toolId!) ? "task/update" : toolId!; const call: ModelToolCall = { id: `qualification-call-${++this.nextId}`, toolId: canonicalToolId, input: input as never }; yield { type: "tool-call", call }; yield { type: "completed" }; }
  private input(toolId: string, parameter: string | undefined, request: ModelRequest) {
    const output = this.lastOutput(request); if (toolId === "task/create") return { objective: "Fix the failing range normalization implementation.", constraints: ["exported API must not change", "only src/range.ts may change", "no test files may change"] };
    if (toolId === "task/add-criterion") return { version: this.version, update: { type: "add_criterion", criterionId: parameter, description: parameter === "tests" ? "tests pass" : parameter === "scope" ? "only intended file changed" : "public API unchanged" } };
    if (toolId === "task/add-step") return { version: this.version, update: { type: "add_step", stepId: parameter, description: parameter } };
    if (toolId === "task/activate") return { version: this.version, update: { type: "set_step_status", stepId: parameter, status: "active" } };
    if (toolId === "task/evidence") return { version: this.version, update: { type: "add_evidence", criterionId: parameter, source: parameter === "tests" ? "execution" : "tool", outcome: "pass", summary: `${parameter} verified by qualification`, toolCallId: `qualification-call-${this.nextId}` } };
    if (toolId === "task/evidence-fail") return { version: this.version, update: { type: "add_evidence", criterionId: "tests", source: "execution", outcome: "fail", summary: "initial verification failed" } };
    if (toolId === "task/complete") return { version: this.version, update: { type: "complete" } };
    if (toolId === "filesystem/patch_file") { return { path: "src/range.ts", expectedHash: this.expectedHash, edits: [{ oldText: "Math.min(min, value)", newText: "Math.min(max, value)", expectedOccurrences: 1 }] }; }
    if (toolId === "artifact/read") { const matches = (output as { matches?: readonly { location: string; line?: number }[] } | undefined)?.matches; const listed = output as readonly { artifactId?: string }[] | undefined; const line = matches?.[0]?.line; return { artifactId: matches?.[0]?.location ?? listed?.[0]?.artifactId ?? "", ...(line ? { startLine: line, endLine: line } : {}) }; }
    if (toolId === "execution/run") return { command: "node", args: ["-e", parameter === "fail" ? failScript : passScript] };
    if (toolId === "artifact/search") return { query: "E2E_ARTIFACT_SENTINEL_4242", limit: 5 };
    if (toolId === "artifact/list") return { limit: 10 };
    if (toolId === "filesystem/search") return { query: "Math.min(min, value)", limit: 10 };
    if (toolId === "filesystem/read_file") return { path: "src/range.ts", mode: "exact" };
    if (toolId === "scratchpad/write") return { key: "diagnosis", content: "The upper-bound branch in src/range.ts clamps against min instead of max." };
    return {};
  }
  private lastOutput(request: ModelRequest): unknown { const message = [...(request.messages ?? [])].reverse().find((entry): entry is Extract<ModelMessage, { role: "tool" }> => entry.role === "tool"); const output = message?.result.output; if (message?.toolId === "execution/run" && output && typeof output === "object" && "exitCode" in output) this.executionExitCodes.push(Number((output as { exitCode: number }).exitCode)); if (message?.toolId === "artifact/read" && output && typeof output === "object" && "content" in output && String((output as { content: string }).content).includes("E2E_ARTIFACT_SENTINEL_4242")) this.artifactHydrated = true; if (message?.toolId === "task/update" && message.result.error?.code === "POLICY_VIOLATION") this.completionRejected++; if ((message?.toolId === "task/update" || message?.toolId === "task/get") && output && typeof output === "object" && "version" in output) this.version = Number((output as { version: number }).version); return output; }
}
function failingCheck() { return "-e"; }
function passingCheck() { return "-e"; }
const failScript = "const fs=require('node:fs'); for(let i=0;i<100;i++) console.log('diagnostic-line-'+i); console.log('E2E_ARTIFACT_SENTINEL_4242'); const s=fs.readFileSync('src/range.ts','utf8'); process.exit(s.includes('Math.min(min, value)')?1:0);";
const passScript = "const fs=require('node:fs'); const s=fs.readFileSync('src/range.ts','utf8'); if(!s.includes('export function clamp')||s.includes('Math.min(min, value)')) process.exit(1); console.log('tests pass; public API preserved');";
// The model inputs use one -e argument; these helpers keep the scripted action names readable.
function failingCheckInput() { return failScript; }
function passingCheckInput() { return passScript; }
function fixture() { const root = mkdtempSync(join(tmpdir(), "porta-e2e-")); execFileSync("git", ["init", "-q", root]); execFileSync("git", ["-C", root, "config", "user.email", "porta@example.invalid"]); execFileSync("git", ["-C", root, "config", "user.name", "Porta E2E"]); writeFileSync(join(root, "src-range.tmp"), "unused"); execFileSync("mkdir", ["-p", join(root, "src")]); writeFileSync(join(root, "src", "range.ts"), "export function clamp(value: number, min: number, max: number): number {\n  return Math.max(min, Math.min(min, value));\n}\n"); writeFileSync(join(root, "src", "other.ts"), "export const unrelated = 1;\n"); execFileSync("git", ["-C", root, "add", "--", "src"]); execFileSync("git", ["-C", root, "commit", "-qm", "broken baseline"]); execFileSync("git", ["-C", root, "clean", "-q", "-fd"]); return root; }
function config(root: string, persistence?: string) { return parsePortaConfig({ model: { provider: "ollama", baseUrl: "http://localhost:11434", model: "qualification" }, filesystem: { root, mutation: { enabled: true } }, execution: { enabled: true, allowedCommands: ["node"], maxStdoutBytes: 128, maxStderrBytes: 128, defaultTimeoutMs: 5000 }, git: { enabled: true, maxDiffBytes: 65536 }, authorization: { mode: "allow-all" }, agent: { maxSteps: 40, maxToolCalls: 100 }, conversation: { maxTurns: 1, compaction: { enabled: true, keepRecentTurns: 1, maxManifestEntries: 20 } }, ...(persistence ? { persistence: { enabled: true, path: persistence } } : {}) }); }
async function runInput(app: Awaited<ReturnType<typeof createPortaApplication>>, sessionId: string, input: string) { const events = []; for await (const event of app.gateway.execute({ type: "SubmitInput", sessionId, input })) events.push(event); return events; }

describe("Porta self-qualification coding loop", () => {
  it("completes a broken repository task through the composed capabilities", async () => { const root = fixture(); const model = new QualificationModel(["task/create", "task/add-criterion|tests", "task/add-criterion|scope", "task/add-criterion|api", "task/add-step|inspect", "task/add-step|implement", "task/add-step|verify", "task/activate|inspect", "filesystem/search", "filesystem/read_file", "text", "execution/run|fail", "artifact/search", "artifact/read", "scratchpad/write", "text", "filesystem/read_file", "filesystem/patch_file", "execution/run|pass", "text", "git/status", "git/diff", "task/complete", "task/evidence|tests", "task/evidence|scope", "task/evidence|api", "task/complete", "text"]); const app = await createPortaApplication(config(root), { model: () => model, executionRuntime: new HostProcessRuntime(), executionSandbox: new HostProcessSandbox(), compactor: new DeterministicConversationCompactor() }); const created = (await runCreate(app)); await runInput(app, created, "start task"); await runInput(app, created, "diagnose and retain the failure"); await runInput(app, created, "continue after diagnosis"); await runInput(app, created, "verify and complete"); const task = await app.tasks.get(created); const status = await app.toolRouter.invoke({ schemaVersion: 1, requestId: "status", toolId: "git/status", input: {} }, context(created)); const diff = await app.toolRouter.invoke({ schemaVersion: 1, requestId: "diff", toolId: "git/diff", input: {} }, context(created)); expect(task?.status).toBe("completed"); expect(model.executionExitCodes).toEqual([1, 0]); expect(model.artifactHydrated).toBe(true); expect(model.completionRejected).toBe(1); expect(task?.evidence.map((entry) => entry.outcome)).toEqual(["pass", "pass", "pass"]); expect(readFileSync(join(root, "src/range.ts"), "utf8")).toContain("Math.min(max, value)"); expect(status).toMatchObject({ ok: true, output: { clean: false, unstaged: ["src/range.ts"] } }); expect(diff).toMatchObject({ ok: true, output: { filesChanged: 1 } }); const compactedRequest = model.requests.find((request) => request.control?.some((message) => message.content.includes("Conversation history was compacted"))); expect(compactedRequest).toBeTruthy(); expect(compactedRequest?.control?.some((message) => message.content.includes("Current task"))).toBe(true); expect(compactedRequest?.control?.some((message) => message.content.includes("Relevant working notes"))).toBe(true); expect(compactedRequest?.control?.some((message) => message.content.includes("Available scratchpad entries"))).toBe(true); expect(JSON.stringify(compactedRequest)).not.toContain("diagnostic-line-50"); expect((JSON.stringify(model.requests).match(/diagnostic-line-/g) ?? []).length).toBeLessThan(100); await app.shutdown(); });

  it("prevents an unapproved mutation in the integrated gateway", async () => { const root = fixture(); const model = new QualificationModel(["filesystem/patch_file", "text"]); const deniedConfig = parsePortaConfig({ ...config(root), authorization: { mode: "require-approval" } }); const app = await createPortaApplication(deniedConfig, { model: () => model, executionRuntime: new HostProcessRuntime(), executionSandbox: new HostProcessSandbox(), compactor: new DeterministicConversationCompactor() }); const session = await runCreate(app); const stream = app.gateway.execute({ type: "SubmitInput", sessionId: session, input: "patch" }); const iterator = stream[Symbol.asyncIterator](); let approval: { approvalId: string } | undefined; for (;;) { const next = await iterator.next(); if (next.done) break; if (next.value.type === "ApprovalRequested") { approval = next.value; break; } } expect(approval).toBeTruthy(); await collect(app.gateway.execute({ type: "ResolveApproval", approvalId: approval!.approvalId, decision: "deny" })); await collect({ [Symbol.asyncIterator]: () => iterator }); expect(readFileSync(join(root, "src/range.ts"), "utf8")).toContain("Math.min(min, value)"); expect((await app.toolRouter.invoke({ schemaVersion: 1, requestId: "status", toolId: "git/status", input: {} }, context(session))).output).toMatchObject({ clean: true }); await app.shutdown(); });

  it("resumes task, scratchpad, conversation, and artifacts across restart", async () => { const root = fixture(); const db = ".porta/e2e.db"; const firstModel = new QualificationModel(["task/create", "task/add-criterion|tests", "task/add-criterion|scope", "task/add-criterion|api", "execution/run|fail", "scratchpad/write", "task/evidence-fail", "text"]); const first = await createPortaApplication(config(root, db), { model: () => firstModel, executionRuntime: new HostProcessRuntime(), executionSandbox: new HostProcessSandbox(), compactor: new DeterministicConversationCompactor() }); const session = await runCreate(first); await runInput(first, session, "begin"); await runInput(first, session, "diagnose"); const artifactList = await first.toolRouter.invoke({ schemaVersion: 1, requestId: "list", toolId: "artifact/list", input: {} }, context(session)); const artifactId = (artifactList.output as readonly { artifactId: string }[])[0]!.artifactId; const before = await first.tasks.get(session); const scratch = await first.scratchpad.read(session, "diagnosis"); expect(before?.evidence[0]?.outcome).toBe("fail"); await first.shutdown(); const secondModel = new QualificationModel(["task/get", "artifact/list", "artifact/read", "filesystem/read_file", "filesystem/patch_file", "execution/run|pass", "git/status", "git/diff", "task/evidence|tests", "task/evidence|scope", "task/evidence|api", "task/complete", "text"]); const second = await createPortaApplication(config(root, db), { model: () => secondModel, executionRuntime: new HostProcessRuntime(), executionSandbox: new HostProcessSandbox(), compactor: new DeterministicConversationCompactor() }); const resumed = await runCreate(second, session); await runInput(second, resumed, "resume and complete"); const after = await second.tasks.get(session); expect(resumed).toBe(session); expect(after?.id).toBe(before?.id); expect(after?.version).toBeGreaterThan(before!.version); expect(after?.evidence.some((entry) => entry.outcome === "fail")).toBe(true); expect(after?.status).toBe("completed"); expect((await second.scratchpad.read(session, "diagnosis"))?.content).toBe(scratch?.content); expect((await second.toolRouter.invoke({ schemaVersion: 1, requestId: "read", toolId: "artifact/read", input: { artifactId } }, context(session))).ok).toBe(true); await second.shutdown(); });
});
async function runCreate(app: Awaited<ReturnType<typeof createPortaApplication>>, sessionId?: string): Promise<string> { const events = await collect(app.gateway.execute({ type: "CreateSession", ...(sessionId ? { sessionId } : {}) })); const event = (events as Array<{ type: string; sessionId?: string }>).find((entry) => entry.type === "SessionCreated"); if (!event?.sessionId) throw new Error(JSON.stringify(events)); return event.sessionId; }
async function collect(source: AsyncIterable<unknown>) { const values: unknown[] = []; for await (const value of source) values.push(value); return values; }
function context(sessionId: string): ToolContext { return { traceId: "e2e", sessionId, executionId: "e2e", signal: new AbortController().signal }; }
