import { describe, expect, it } from "vitest";
import { mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { FilesystemToolProvider } from "../src/filesystem.js";
import { ScratchpadToolProvider, MemoryScratchpadStore } from "../src/scratchpad.js";
import { ConversationTurn, ToolContext, ToolInvocation } from "../src/contracts.js";
import { MemoryConversationStore, sessionFromBase } from "../src/conversation.js";

const context = (sessionId = "session-a"): ToolContext => ({ traceId: "trace", sessionId, executionId: "execution", signal: new AbortController().signal });
const invocation = (toolId: string, input: unknown): ToolInvocation => ({ schemaVersion: 1, requestId: toolId, toolId, input: input as never });

async function fixture() { const root = mkdtempSync(join(tmpdir(), "porta-filesystem-")); writeFileSync(join(root, "small.txt"), "line one\nline two\nline three\n"); writeFileSync(join(root, "large.txt"), "SECRET_FULL_SOURCE_SENTINEL_92741\n".repeat(10)); writeFileSync(join(root, "binary.bin"), Buffer.from([1, 2, 0, 3])); await fs.mkdir(join(root, "dir")); writeFileSync(join(root, "dir", "nested.txt"), "nested"); return root; }

describe("read-only filesystem tools", () => {
  it("reads exact content and inclusive line ranges", async () => { const root = await fixture(); const provider = new FilesystemToolProvider({ root }); const exact = await provider.invoke(invocation("read_file", { path: "small.txt" }), context()); expect(exact).toMatchObject({ ok: true, output: { mode: "exact", content: "line one\nline two\nline three\n" } }); const range = await provider.invoke(invocation("read_file", { path: "small.txt", range: { startLine: 2, endLine: 2 } }), context()); expect(range).toMatchObject({ ok: true, output: { content: "line two" } }); });
  it("summarizes without returning source to the parent result", async () => { const root = await fixture(); let reduced = ""; const provider = new FilesystemToolProvider({ root }, { reduce: async (request) => { reduced = request.content; return { content: "SUMMARY_SENTINEL_118", sourceChars: request.content.length }; } }); const result = await provider.invoke(invocation("read_file", { path: "large.txt", mode: "summary" }), context()); expect(result).toMatchObject({ ok: true, output: { summary: "SUMMARY_SENTINEL_118", mode: "summary" } }); expect(JSON.stringify(result)).not.toContain("SECRET_FULL_SOURCE_SENTINEL_92741"); expect(reduced).toContain("SECRET_FULL_SOURCE_SENTINEL_92741"); });
  it("rejects oversized exact context but allows bounded reads for reduction", async () => { const root = await fixture(); const provider = new FilesystemToolProvider({ root, maxExactContextBytes: 8, maxReadBytes: 4096 }); expect((await provider.invoke(invocation("read_file", { path: "large.txt" }), context())).ok).toBe(false); expect((await provider.invoke(invocation("read_file", { path: "large.txt", mode: "summary" }), context())).ok).toBe(true); });
  it("lists deterministically and stats files/directories", async () => { const root = await fixture(); const provider = new FilesystemToolProvider({ root }); const listing = await provider.invoke(invocation("list_directory", { path: "." }), context()); expect((listing as unknown as { output: { entries: { name: string }[] } }).output.entries.map((entry) => entry.name)).toEqual(["binary.bin", "dir", "large.txt", "small.txt"]); expect(await provider.invoke(invocation("stat", { path: "dir" }), context())).toMatchObject({ ok: true, output: { kind: "directory" } }); });
  it("fails closed for traversal, directories, binary, and invalid ranges", async () => { const root = await fixture(); const provider = new FilesystemToolProvider({ root }); for (const path of ["../outside", "/etc/passwd"]) expect((await provider.invoke(invocation("stat", { path }), context())).ok).toBe(false); expect((await provider.invoke(invocation("read_file", { path: "dir" }), context())).ok).toBe(false); expect((await provider.invoke(invocation("read_file", { path: "binary.bin" }), context())).ok).toBe(false); expect((await provider.invoke(invocation("read_file", { path: "small.txt", range: { startLine: 3, endLine: 2 } }), context())).ok).toBe(false); });
  it("rejects symlink escapes", async () => { const root = await fixture(); const outside = mkdtempSync(join(tmpdir(), "porta-outside-")); writeFileSync(join(outside, "secret"), "outside"); try { symlinkSync(join(outside, "secret"), join(root, "escape")); const provider = new FilesystemToolProvider({ root }); expect((await provider.invoke(invocation("read_file", { path: "escape" }), context())).ok).toBe(false); } finally { /* temporary directories are cleaned by the test environment */ } });
});

describe("session-scoped agent scratchpad", () => {
  it("keeps notes after conversation budget drops old turns", async () => { const notes = new MemoryScratchpadStore(); const conversations = new MemoryConversationStore({ maxTurns: 1 }); await conversations.createSession(sessionFromBase({ schemaVersion: 1, id: "a", state: "open", createdAt: "now" })); await notes.write("a", "important", "SCRATCHPAD_DURABLE_SENTINEL_8127"); const turn = (content: string): ConversationTurn => ({ messages: [{ role: "user", content }, { role: "assistant", content: "done" }] }); await conversations.commitTurn("a", turn("one")); await conversations.commitTurn("a", turn("two")); expect((await conversations.snapshot("a")).turnsDropped).toBe(1); expect((await notes.read("a", "important"))?.content).toBe("SCRATCHPAD_DURABLE_SENTINEL_8127"); });
  it("writes, appends, lists metadata, reads explicitly, and isolates sessions", async () => { const store = new MemoryScratchpadStore(); const provider = new ScratchpadToolProvider(store); const write = await provider.invoke(invocation("write", { key: "architecture-findings", content: "SCRATCHPAD_PRIVATE_SENTINEL_728" }), context("a")); expect(JSON.stringify(write)).not.toContain("SCRATCHPAD_PRIVATE_SENTINEL_728"); await provider.invoke(invocation("append", { key: "architecture-findings", content: " + more" }), context("a")); const list = await provider.invoke(invocation("list", {}), context("a")); expect(JSON.stringify(list)).not.toContain("SCRATCHPAD_PRIVATE_SENTINEL_728"); expect(await provider.invoke(invocation("read", { key: "architecture-findings" }), context("a"))).toMatchObject({ ok: true, output: { content: "SCRATCHPAD_PRIVATE_SENTINEL_728 + more" } }); expect((await provider.invoke(invocation("read", { key: "architecture-findings" }), context("b"))).ok).toBe(false); });
});
