import { describe, expect, it } from "vitest";
import { existsSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { FilesystemToolProvider } from "../src/filesystem.js";
import { DirectFilesystemMutationEngine, contentHash } from "../src/mutation.js";
import { WorkspaceBoundary } from "../src/workspace.js";
import { ToolContext, ToolInvocation } from "../src/contracts.js";
import { ToolRouter } from "../src/tools.js";
import { ScriptedToolModelProvider } from "../src/agent-mocks.js";
import { AgentOrchestrator } from "../src/agent.js";
import { StaticToolAuthorizationPolicy } from "../src/authorization-mocks.js";
import { PendingApprovalProvider } from "../src/approval-pending.js";
import { InteractiveApprovalGateway } from "../src/application-gateway.js";
import { KernelEvent } from "../src/contracts.js";

const context = (signal = new AbortController().signal): ToolContext => ({ traceId: "trace", sessionId: "session", executionId: "execution", signal });
const invoke = (toolId: string, input: unknown): ToolInvocation => ({ schemaVersion: 1, requestId: toolId, toolId, input: input as never });
async function root() { const value = mkdtempSync(join(tmpdir(), "porta-mutation-")); writeFileSync(join(value, "file.txt"), "alpha\nbeta\n"); return value; }

 describe("filesystem mutation", () => {
  it("creates, replaces, patches, and verifies hashes", async () => { const dir = await root(); const provider = new FilesystemToolProvider({ root: dir, mutation: { enabled: true } }); const created = await provider.invoke(invoke("write_file", { path: "new.txt", content: "created", mode: "create" }), context()); expect(created).toMatchObject({ ok: true, output: { operation: "write", changed: true, verified: true } }); const before = contentHash(Buffer.from("alpha\nbeta\n")); const patched = await provider.invoke(invoke("patch_file", { path: "file.txt", expectedHash: before, edits: [{ oldText: "beta", newText: "gamma" }] }), context()); expect(patched).toMatchObject({ ok: true, output: { operation: "patch", beforeHash: before, verified: true } }); expect(readFileSync(join(dir, "file.txt"), "utf8")).toBe("alpha\ngamma\n"); });
  it("requires explicit create/replace semantics", async () => { const dir = await root(); const provider = new FilesystemToolProvider({ root: dir, mutation: { enabled: true } }); expect((await provider.invoke(invoke("write_file", { path: "file.txt", content: "x", mode: "create" }), context())).ok).toBe(false); expect((await provider.invoke(invoke("write_file", { path: "missing.txt", content: "x", mode: "replace" }), context())).ok).toBe(false); expect((await provider.invoke(invoke("write_file", { path: "file.txt", content: "x", mode: "replace" }), context())).ok).toBe(true); });
  it("rejects stale and ambiguous patches without changing the file", async () => { const dir = await root(); const provider = new FilesystemToolProvider({ root: dir, mutation: { enabled: true } }); const oldHash = contentHash(Buffer.from("alpha\nbeta\n")); writeFileSync(join(dir, "file.txt"), "external\n"); expect((await provider.invoke(invoke("patch_file", { path: "file.txt", expectedHash: oldHash, edits: [{ oldText: "external", newText: "changed" }] }), context())).ok).toBe(false); expect(readFileSync(join(dir, "file.txt"), "utf8")).toBe("external\n"); writeFileSync(join(dir, "file.txt"), "x x"); expect((await provider.invoke(invoke("patch_file", { path: "file.txt", edits: [{ oldText: "x", newText: "y" }] }), context())).ok).toBe(false); expect(readFileSync(join(dir, "file.txt"), "utf8")).toBe("x x"); });
  it("confines mutation and rejects symlinks, directories, binary files, and oversized writes", async () => { const dir = await root(); const outside = mkdtempSync(join(tmpdir(), "porta-outside-mutation-")); writeFileSync(join(outside, "secret"), "secret"); symlinkSync(join(outside, "secret"), join(dir, "escape")); writeFileSync(join(dir, "binary"), Buffer.from([0, 1])); await fs.mkdir(join(dir, "folder")); const provider = new FilesystemToolProvider({ root: dir, mutation: { enabled: true, maxWriteBytes: 3 } }); for (const input of [{ path: "../outside", content: "x", mode: "create" }, { path: "escape", content: "x", mode: "replace" }, { path: "folder", content: "x", mode: "replace" }, { path: "binary", content: "x", mode: "replace" }, { path: "large", content: "long", mode: "create" }]) expect((await provider.invoke(invoke("write_file", input), context())).ok).toBe(false); });
  it("keeps mutation tools absent when disabled and cancellation before commit changes nothing", async () => { const dir = await root(); const readonly = new FilesystemToolProvider({ root: dir }); expect((await readonly.listTools(context())).some((tool) => tool.id === "write_file")).toBe(false); const controller = new AbortController(); controller.abort(); const engine = new DirectFilesystemMutationEngine(new WorkspaceBoundary(dir)); await expect(engine.write({ path: "new.txt", content: "x", mode: "create" }, context(controller.signal))).rejects.toMatchObject({ error: { code: "CANCELLED" } }); expect(existsSync(join(dir, "new.txt"))).toBe(false); });
  it("approval approval performs exactly one mutation", async () => { const dir = await root(); const provider = new FilesystemToolProvider({ root: dir, mutation: { enabled: true } }); const router = new ToolRouter(); await router.register("filesystem", provider, context()); const pending = new PendingApprovalProvider(); const gateway = new InteractiveApprovalGateway(new ScriptedToolModelProvider([[{ type: "tool", id: "write-call", toolId: "filesystem/write_file", input: { path: "approved.txt", content: "yes", mode: "create" } }], [{ type: "text", text: "done" }]]), router, pending, new StaticToolAuthorizationPolicy("require-approval")); const created = (await collect(gateway.execute({ type: "CreateSession" }, {})))[0] as Extract<KernelEvent, { type: "SessionCreated" }>; const iterator = gateway.execute({ type: "SubmitInput", sessionId: created.sessionId, input: "write" }, {})[Symbol.asyncIterator](); const requested = await nextUntil(iterator, "ApprovalRequested") as Extract<KernelEvent, { type: "ApprovalRequested" }>; expect(existsSync(join(dir, "approved.txt"))).toBe(false); await collect(gateway.execute({ type: "ResolveApproval", approvalId: requested.approvalId, decision: "approve" }, {})); await collect({ [Symbol.asyncIterator]: () => iterator }); expect(readFileSync(join(dir, "approved.txt"), "utf8")).toBe("yes"); });

  it("authorization denial performs zero mutation", async () => { const dir = await root(); const provider = new FilesystemToolProvider({ root: dir, mutation: { enabled: true } }); const router = new ToolRouter(); await router.register("filesystem", provider, context()); const model = new ScriptedToolModelProvider([[{ type: "tool", id: "write-call", toolId: "filesystem/write_file", input: { path: "denied.txt", content: "no", mode: "create" } }], [{ type: "text", text: "denied" }]]); const execution = new AgentOrchestrator(model, router, undefined, { policy: new StaticToolAuthorizationPolicy("deny"), approvalProvider: new PendingApprovalProvider() }).create("write", context(), router.listTools()); await collect(execution.events()); expect(existsSync(join(dir, "denied.txt"))).toBe(false); });
 });
async function collect<T>(source: AsyncIterable<T>): Promise<T[]> { const values: T[] = []; for await (const value of source) values.push(value); return values; }
async function nextUntil<T extends { type: string }>(iterator: AsyncIterator<T>, type: string): Promise<T> { for (;;) { const item = await iterator.next(); if (item.done) throw new Error(`Expected ${type}`); if (item.value.type === type) return item.value; } }
