import { describe, expect, it } from "vitest";
import { mkdtempSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { openSqlitePersistence } from "../src/persistence-sqlite.js";
import { sessionFromBase } from "../src/conversation.js";
import { ConversationTurn } from "../src/contracts.js";
import { PendingApprovalProvider } from "../src/approval-pending.js";
import { DurableExecution } from "../src/execution-persistence.js";

function dbPath() { return join(mkdtempSync(join(tmpdir(), "porta-db-")), "nested", "porta.db"); }
const session = (id = "session-persist") => sessionFromBase({ schemaVersion: 1, id, state: "open", createdAt: new Date().toISOString() });

describe("SQLite persistent stores", () => {
  it("restores conversation turns, scratchpad, and task evidence across reopen", async () => { const path = dbPath(); const first = await openSqlitePersistence(path); await first.conversations.createSession(session()); const turn: ConversationTurn = { messages: [{ role: "user", content: "PERSISTED_USER" }, { role: "assistant", content: "PERSISTED_ASSISTANT", toolCalls: [{ id: "call-1", toolId: "task/create", input: { objective: "x" } }] }, { role: "tool", toolCallId: "call-1", toolId: "task/create", result: { toolCallId: "call-1", toolId: "task/create", output: { status: "active" } } }] }; await first.conversations.commitTurn("session-persist", turn); await first.scratchpad.write("session-persist", "notes", "PERSISTENT_SCRATCHPAD_SENTINEL_812"); const artifact = await first.artifacts.put("session-persist", { kind: "log", contentType: "text/plain", content: "PERSISTENT_ARTIFACT_SENTINEL_991", source: "test" }); const task = await first.tasks.create("session-persist", "PERSISTENT_TASK", ["no loss"], { goal: "PERSISTENT_DEVELOPMENT", acceptanceCriteria: ["tests pass"], workspace: { path: "/tmp/fixture" }, permissions: { mutate: true, commit: false, push: false, deploy: false }, focusedCommands: ["npm test"], fullCommands: ["npm test", "npm run typecheck"], phase: "awaiting_approval", attention: { reason: "approval_required", message: "PERSISTENT_APPROVAL" }, pendingIntervention: { action: "approve", message: "PERSISTENT_APPROVAL", requestedAt: "2024-01-01T00:00:00.000Z" }, updatedAt: "2024-01-01T00:00:00.000Z" }); let current = task; current = await first.tasks.update("session-persist", current.id, current.version, { type: "add_criterion", criterionId: "tests", description: "tests pass" }); current = await first.tasks.update("session-persist", current.id, current.version, { type: "add_evidence", criterionId: "tests", source: "execution", outcome: "fail", summary: "run one", executionId: "exec-1" }); current = await first.tasks.update("session-persist", current.id, current.version, { type: "add_evidence", criterionId: "tests", source: "execution", outcome: "pass", summary: "run two", executionId: "exec-2" }); expect(current.version).toBe(4); first.close();
    const second = await openSqlitePersistence(path); const restored = await second.conversations.getSession("session-persist"); expect(restored?.turns).toEqual([turn]); expect((await second.scratchpad.read("session-persist", "notes"))?.content).toBe("PERSISTENT_SCRATCHPAD_SENTINEL_812"); const restoredArtifact = await second.artifacts.get("session-persist", artifact.uri); expect(restoredArtifact?.content).toBe("PERSISTENT_ARTIFACT_SENTINEL_991"); expect(restoredArtifact?.metadata.sha256).toBe(artifact.sha256); const restoredTask = await second.tasks.get("session-persist"); expect(restoredTask?.version).toBe(4); expect(restoredTask?.evidence.map((entry) => entry.outcome)).toEqual(["fail", "pass"]); expect(restoredTask?.development?.phase).toBe("awaiting_approval"); expect(restoredTask?.development?.pendingIntervention?.action).toBe("approve"); const stale = await second.tasks.update("session-persist", restoredTask!.id, 1, { type: "set_status", status: "blocked" }).catch((error) => error); expect(stale).toMatchObject({ error: { code: "CAPABILITY_CONFLICT" } }); second.close(); });
  it("restores pending approvals with stable identity across reopen", async () => { const path = dbPath(); const first = await openSqlitePersistence(path); await first.conversations.createSession(session("approval-session")); const record = { type: "ApprovalRequested" as const, approvalId: "approval-persist-1", toolCallId: "call-1", toolId: "task/create", input: { objective: "persist me" }, executionId: "exec-1", sessionId: "approval-session", traceId: "trace-1" }; first.approvals.save(record); first.close(); const second = await openSqlitePersistence(path); const pending = new PendingApprovalProvider(second.approvals); expect(pending.pendingRequests()).toEqual([record]); second.close(); const third = await openSqlitePersistence(path); const hydratedAgain = new PendingApprovalProvider(third.approvals); expect(hydratedAgain.pendingRequests()).toEqual([record]); expect(hydratedAgain.resolve(record.approvalId, { decision: "deny", reason: "after restart" })).toMatchObject({ approvalId: record.approvalId, decision: "deny" }); expect(third.approvals.list()).toEqual([]); third.close(); });
  it("persists versioned execution checkpoints and lists only incomplete work", async () => { const path = dbPath(); const first = await openSqlitePersistence(path); await first.conversations.createSession(session("execution-session")); const now = new Date().toISOString(); const checkpoint: DurableExecution = { executionId: "execution-stable", sessionId: "execution-session", traceId: "trace-stable", phase: "approval_required", version: 1, input: "continue", history: [{ role: "user", content: "continue" }], currentToolCall: { id: "call-stable", toolId: "filesystem/read", input: { path: "README.md" } }, approvalId: "approval-stable", createdAt: now, updatedAt: now }; first.executions.save(checkpoint); first.close(); const second = await openSqlitePersistence(path); expect(second.executions.get("execution-stable")?.executionId).toBe("execution-stable"); expect(second.executions.listIncomplete().map((entry) => entry.executionId)).toEqual(["execution-stable"]); expect(() => second.executions.save({ ...checkpoint, phase: "completed", version: 2, updatedAt: new Date().toISOString() }, 99)).toThrow(); second.executions.save({ ...checkpoint, phase: "completed", version: 2, updatedAt: new Date().toISOString() }, 1); expect(second.executions.listIncomplete()).toEqual([]); second.close(); });
  it("keeps sessions isolated and preserves scratchpad search inputs", async () => { const path = dbPath(); const persistence = await openSqlitePersistence(path); await persistence.conversations.createSession(session("a")); await persistence.conversations.createSession(session("b")); await persistence.scratchpad.write("a", "key", "alpha"); await persistence.scratchpad.write("b", "key", "beta"); expect((await persistence.scratchpad.read("a", "key"))?.content).toBe("alpha"); expect((await persistence.scratchpad.read("b", "key"))?.content).toBe("beta"); expect(persistence.conversations.openSessionIds()).toEqual(["a", "b"]); persistence.close(); });
});
