import { describe, expect, it } from "vitest";
import { mkdtempSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { openSqlitePersistence } from "../src/persistence-sqlite.js";
import { sessionFromBase } from "../src/conversation.js";
import { ConversationTurn } from "../src/contracts.js";

function dbPath() { return join(mkdtempSync(join(tmpdir(), "porta-db-")), "nested", "porta.db"); }
const session = (id = "session-persist") => sessionFromBase({ schemaVersion: 1, id, state: "open", createdAt: new Date().toISOString() });

describe("SQLite persistent stores", () => {
  it("restores conversation turns, scratchpad, and task evidence across reopen", async () => { const path = dbPath(); const first = await openSqlitePersistence(path); await first.conversations.createSession(session()); const turn: ConversationTurn = { messages: [{ role: "user", content: "PERSISTED_USER" }, { role: "assistant", content: "PERSISTED_ASSISTANT", toolCalls: [{ id: "call-1", toolId: "task/create", input: { objective: "x" } }] }, { role: "tool", toolCallId: "call-1", toolId: "task/create", result: { toolCallId: "call-1", toolId: "task/create", output: { status: "active" } } }] }; await first.conversations.commitTurn("session-persist", turn); await first.scratchpad.write("session-persist", "notes", "PERSISTENT_SCRATCHPAD_SENTINEL_812"); const task = await first.tasks.create("session-persist", "PERSISTENT_TASK", ["no loss"]); let current = task; current = await first.tasks.update("session-persist", current.id, current.version, { type: "add_criterion", criterionId: "tests", description: "tests pass" }); current = await first.tasks.update("session-persist", current.id, current.version, { type: "add_evidence", criterionId: "tests", source: "execution", outcome: "fail", summary: "run one", executionId: "exec-1" }); current = await first.tasks.update("session-persist", current.id, current.version, { type: "add_evidence", criterionId: "tests", source: "execution", outcome: "pass", summary: "run two", executionId: "exec-2" }); expect(current.version).toBe(4); first.close();
    const second = await openSqlitePersistence(path); const restored = await second.conversations.getSession("session-persist"); expect(restored?.turns).toEqual([turn]); expect((await second.scratchpad.read("session-persist", "notes"))?.content).toBe("PERSISTENT_SCRATCHPAD_SENTINEL_812"); const restoredTask = await second.tasks.get("session-persist"); expect(restoredTask?.version).toBe(4); expect(restoredTask?.evidence.map((entry) => entry.outcome)).toEqual(["fail", "pass"]); const stale = await second.tasks.update("session-persist", restoredTask!.id, 1, { type: "set_status", status: "blocked" }).catch((error) => error); expect(stale).toMatchObject({ error: { code: "CAPABILITY_CONFLICT" } }); second.close(); });
  it("keeps sessions isolated and preserves scratchpad search inputs", async () => { const path = dbPath(); const persistence = await openSqlitePersistence(path); await persistence.conversations.createSession(session("a")); await persistence.conversations.createSession(session("b")); await persistence.scratchpad.write("a", "key", "alpha"); await persistence.scratchpad.write("b", "key", "beta"); expect((await persistence.scratchpad.read("a", "key"))?.content).toBe("alpha"); expect((await persistence.scratchpad.read("b", "key"))?.content).toBe("beta"); expect(persistence.conversations.openSessionIds()).toEqual(["a", "b"]); persistence.close(); });
});
