import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = join(process.cwd(), "integrations", "chatgpt-browser-extension");
const content = readFileSync(join(root, "content.js"), "utf8"); const client = readFileSync(join(root, "porta-client.js"), "utf8"); const background = readFileSync(join(root, "background.js"), "utf8"); const manifest = JSON.parse(readFileSync(join(root, "manifest.json"), "utf8"));

describe("ChatGPT Porta extension", () => {
  it("uses explicit user action and idempotent artifact controls", () => { expect(content).toContain("button.onclick"); expect(content).not.toContain("button.textContent = \"Send to Porta ▾\""); expect(content).toContain("MutationObserver"); expect(content).toContain("data-porta-control"); expect(content).toContain("crypto.randomUUID()"); expect(content).toContain("processedCopyActions"); expect(content).not.toContain("setInterval"); });
  it("anchors extraction to native Copy actions without privileged Porta operations", () => { expect(content).toContain("aria-label"); expect(content).toContain("kopieren"); expect(content).toContain("copy"); expect(content).toContain("editor öffnen"); expect(content).toContain("open editor"); expect(content).toContain("writing-block-header-surface"); expect(content).toContain("writingBlockHeaderFor"); expect(content).toContain("isNativeCopyButton"); expect(content).toContain("isOpenEditorButton"); expect(content).toContain("findArtifactForCopyButton"); expect(content).toContain("writing-block"); expect(content).toContain("HTMLTextAreaElement"); expect(content).toContain("source.value"); expect(content).toContain("code.textContent"); expect(content).not.toContain("innerText"); expect(content).not.toContain("findAssistantArtifacts"); expect(content).not.toContain("renderedToMarkdown"); expect(client).toContain("chrome.runtime.sendMessage"); expect(content).not.toMatch(/ssh|docker|filesystem|execution\.run/i); });
  it("coalesces streaming mutations and ignores extension-owned DOM", () => { expect(content).toContain("scopeTimers"); expect(content).toContain("setTimeout(() =>"); expect(content).toContain("extensionOwned(node)"); expect(content).toContain("addedNodes"); expect(content).toContain("processScope(document)"); expect(content).not.toContain("scan()"); });
  it("preserves separate code and Writing Block artifact adapters", () => { expect(content).toContain('type: "code"'); expect(content).toContain('type: "writing-block"'); expect(content).toContain("findCodeArtifactForCopyButton"); expect(content).toContain("findWritingBlockArtifact"); expect(content).not.toContain(".markdown"); expect(content).not.toContain(".prose"); });
  it("mounts beside the native action and avoids legacy trailing injection", () => { expect(content).toContain("actionContainer.append(container)"); expect(content).toContain("child.matches?.(`[${MARKER}]`)"); expect(content).not.toContain("artifact.nextElementSibling"); });
  it("uses an accessible inline squirrel icon button", () => { expect(content).toContain("porta-send-button"); expect(content).toContain('aria-label\", \"Send to Porta'); expect(content).toContain("button.title = \"Send to Porta\""); expect(content).toContain('width=\"20\"'); expect(content).toContain('height=\"20\"'); expect(content).toContain('stroke=\"currentColor\"'); expect(content).toContain('aria-hidden=\"true\"'); expect(content).toContain("button.setAttribute(MARKER, \"true\")"); expect(content).not.toContain('button.textContent = "Send to Porta ▾"'); });
  it("uses a scoped extension origin and no embedded credential", () => { expect(manifest.manifest_version).toBe(3); expect(manifest.optional_host_permissions).toEqual(expect.arrayContaining(["https://*/*"])); expect(manifest.background.service_worker).toBe("background.js"); expect(background).toContain("Authorization"); expect(client).not.toContain("Authorization"); expect(client).not.toContain("chrome.storage"); expect(background).toContain("UNKNOWN_EXTENSION_ACTION"); expect(background).toContain("sessionMappings"); expect(background).toContain("sessionId"); expect(background).not.toContain("message.url"); });
});
