import { describe, expect, it } from "vitest";
import { canRun, driftLevel, reconcileTasks, selectRunnable, shouldQuiesce, type EngineeringTask } from "../src/supervisor.js";
const task = (id: string, status: EngineeringTask["status"], areas: string[], dependsOn: string[] = []): EngineeringTask => ({ id, objective: id, kind: "implementation", status, repository: "vBuf", targetBranch: "main", dependsOn, blockedBy: [], expectedAreas: areas, actualAreas: [], createdAt: "now", updatedAt: "now" });
describe("engineering supervisor", () => {
  it("continues independent work around a blocker", () => { const a = task("a", "blocked", ["runtime"]); const b = task("b", "ready", ["storage"]); expect(canRun(b, [a, b])).toBe(true); expect(selectRunnable([a, b], 1).map((x) => x.id)).toEqual(["b"]); });
  it("respects dependencies", () => { const a = task("a", "running", ["runtime"]); const b = task("b", "ready", ["runtime"], ["a"]); expect(canRun(b, [a, b])).toBe(false); });
  it("avoids overlapping work and allows independent work", () => { const a = task("a", "ready", ["runtime/residency"]); const b = task("b", "ready", ["runtime/residency"]); const c = task("c", "ready", ["storage"]); expect(selectRunnable([a, b], 2)).toHaveLength(1); expect(selectRunnable([a, c], 2).map((x) => x.id)).toEqual(["a", "c"]); });
  it("classifies drift and refuses quiescence while findings exist", () => { expect(driftLevel({ baseCommit: "a", targetCommit: "b", featureCommit: "c", targetFiles: [], featureFiles: ["storage"] })).toBe("LOW"); expect(driftLevel({ baseCommit: "a", targetCommit: "b", featureCommit: "c", targetFiles: ["runtime/executor"], featureFiles: ["runtime/executor", "runtime/x", "runtime/y"] })).toBe("HIGH"); expect(shouldQuiesce({ tasks: [task("a", "blocked", ["x"])], findings: ["audit"], humanBlockers: ["hardware"] })).toBe(false); expect(shouldQuiesce({ tasks: [task("a", "blocked", ["x"])], findings: [], humanBlockers: ["hardware"] })).toBe(true); });
  it("reconciles running tasks after process restart", () => { const result = reconcileTasks([task("a", "running", ["x"])]); expect(result[0]).toMatchObject({ status: "failed", result: "execution_interrupted" }); });
});
