import { describe, expect, it } from "vitest";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { InstanceIdentityStore } from "../src/identity.js";
import { InMemoryTargetTransport, createTargetTransportServer } from "../src/target-transport.js";
import { PairingSession, pairingFingerprint, pairingUrl } from "../src/target-pairing.js";

describe("target pairing bootstrap", () => {
  it("is single-use and expires", () => { const session = new PairingSession(new Date(Date.now() + 60_000).toISOString(), "token"); expect(session.consume("wrong")).toBe(false); expect(session.consume("token")).toBe(true); expect(session.consume("token")).toBe(false); const expired = new PairingSession(new Date(Date.now() - 1).toISOString(), "expired"); expect(expired.consume("expired")).toBe(false); });
  it("routes pairing separately from normal authenticated operations", async () => { const serverDir = mkdtempSync(join(tmpdir(), "porta-pair-server-")); const clientDir = mkdtempSync(join(tmpdir(), "porta-pair-client-")); const serverIdentity = new InstanceIdentityStore(serverDir); const clientIdentity = new InstanceIdentityStore(clientDir); const description = { id: "pc-main", kind: "development-pc", available: true, capabilities: ["execution.run"] as const, workspace: { id: "porta-main", path: "/workspace" } }; const pairing = new PairingSession(new Date(Date.now() + 60_000).toISOString(), "pair-token"); const server = createTargetTransportServer({ target: description, identity: serverIdentity, operations: new InMemoryTargetTransport(description), pairing }); const address = await server.listen(); try { const challenge = await (await fetch(`http://${address.host}:${address.port}/target/pair/challenge`, { method: "POST" })).json(); const request = { version: 1, type: "porta-target-pairing" as const, targetId: "pc-main", workspaceId: "porta-main", pairingToken: "pair-token", challengeId: challenge.challengeId, signature: clientIdentity.sign(challenge), orchestrator: clientIdentity.public }; const response = await fetch(`http://${address.host}:${address.port}/target/pair`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(request) }); expect(response.status).toBe(200); expect(serverIdentity.isAllowed(clientIdentity.public.identity)).toBe(true); const reused = await fetch(`http://${address.host}:${address.port}/target/pair`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(request) }); expect(reused.status).toBe(401); expect(pairingFingerprint(serverIdentity.public.identity)).toMatch(/^[0-9a-f]{64}$/); expect(pairingUrl({ version: 1, type: "porta-target-pairing", targetId: "pc-main", workspaceId: "porta-main", endpoint: "http://pc:1", identityFingerprint: pairingFingerprint(serverIdentity.public.identity), pairingToken: "temporary", expiresAt: new Date(Date.now() + 60_000).toISOString() }, "http://host:4173")).toContain("http://host:4173/app#porta-target-pairing="); } finally { await server.close(); rmSync(serverDir, { recursive: true, force: true }); rmSync(clientDir, { recursive: true, force: true }); } });
});
