import { describe, expect, it } from "vitest";
import { StaticApprovalProvider, StaticToolAuthorizationPolicy } from "../src/authorization-mocks.js";
import { TargetInvocationService } from "../src/target-invocation.js";
import { TargetRegistry } from "../src/target.js";
import type { TargetOperation } from "../src/target-transport.js";

const target = (calls: string[]) => ({ id: "pc-main", kind: "remote", workspace: { id: "porta-main", path: "/pc" }, async available() { return true; }, async capabilities() { return ["execution.run", "filesystem.read", "filesystem.write"] as const; }, async invoke(operation: TargetOperation, input: unknown) { calls.push(`${operation}:${JSON.stringify(input)}`); return { requestId: "x", targetId: "pc-main", operation, status: "completed" as const, output: { remote: true }, startedAt: new Date().toISOString(), finishedAt: new Date().toISOString() }; } });

async function wait(service: TargetInvocationService, id: string) { for (let i = 0; i < 50; i++) { const value = service.get(id); if (value?.status !== "pending") return value; await new Promise((resolve) => setTimeout(resolve, 2)); } return service.get(id); }

describe("orchestrator target invocation", () => {
  it("resolves the registry target and returns target-bound evidence", async () => { const calls: string[] = []; const registry = new TargetRegistry(); registry.register(target(calls)); const service = new TargetInvocationService(registry, new StaticToolAuthorizationPolicy("allow"), new StaticApprovalProvider()); const pending = service.start({ targetId: "pc-main", workspaceId: "porta-main", operation: "execution.run", input: { command: "node", args: ["--version"] } }); const result = await wait(service, pending.invocationId); expect(result).toMatchObject({ targetId: "pc-main", workspaceId: "porta-main", capability: "execution.run", status: "completed", output: { remote: true } }); expect(calls).toHaveLength(1); });
  it("requires orchestrator approval and does not invoke when denied", async () => { const calls: string[] = []; const registry = new TargetRegistry(); registry.register(target(calls)); const approvals = new StaticApprovalProvider(false, "denied by test"); const service = new TargetInvocationService(registry, new StaticToolAuthorizationPolicy("require-approval"), approvals); const pending = service.start({ targetId: "pc-main", workspaceId: "porta-main", operation: "execution.run", input: { command: "node" } }); const result = await wait(service, pending.invocationId); expect(result?.status).toBe("denied"); expect(approvals.requests).toHaveLength(1); expect(calls).toHaveLength(0); });
  it("normalizes requested cancellation but preserves unexpected abort as failure", async () => {
    const registry = new TargetRegistry(); registry.register({ id: "pc-main", kind: "remote", workspace: { id: "porta-main", path: "/pc" }, async available() { return true; }, async capabilities() { return ["execution.run"] as const; }, async invoke(_operation, _input, context) { await new Promise<void>((resolve, reject) => { context?.signal?.addEventListener("abort", () => reject(new Error("This operation was aborted")), { once: true }); }); throw new Error("unreachable"); } }); const service = new TargetInvocationService(registry, new StaticToolAuthorizationPolicy("allow"), new StaticApprovalProvider()); const pending = service.start({ targetId: "pc-main", workspaceId: "porta-main", operation: "execution.run", input: { command: "node" } }); await new Promise((resolve) => setTimeout(resolve, 5)); service.cancel(pending.invocationId); expect((await wait(service, pending.invocationId))?.status).toBe("cancelled");
    const failing = new TargetRegistry(); failing.register({ id: "pc-main", kind: "remote", workspace: { id: "porta-main", path: "/pc" }, async available() { return true; }, async capabilities() { return ["execution.run"] as const; }, async invoke() { throw new Error("unexpected network abort"); } }); const failed = new TargetInvocationService(failing, new StaticToolAuthorizationPolicy("allow"), new StaticApprovalProvider()); expect((await wait(failed, failed.start({ targetId: "pc-main", workspaceId: "porta-main", operation: "execution.run", input: { command: "node" } }).invocationId))?.status).toBe("failed");
  });

  it("fails closed for workspace mismatch and unavailable targets", async () => { const registry = new TargetRegistry(); registry.register(target([])); const service = new TargetInvocationService(registry, new StaticToolAuthorizationPolicy("allow"), new StaticApprovalProvider()); const mismatch = await wait(service, service.start({ targetId: "pc-main", workspaceId: "wrong", operation: "filesystem.read", input: { path: "package.json" } }).invocationId); const missing = await wait(service, service.start({ targetId: "missing", workspaceId: "porta-main", operation: "filesystem.read", input: {} }).invocationId); expect(mismatch?.error?.code).toBe("WORKSPACE_MISMATCH"); expect(missing?.error?.code).toBe("TARGET_UNAVAILABLE"); });
});
