import { describe, expect, it } from "vitest";
import { MemoryTaskStore, TaskToolProvider, criterionState } from "../src/task.js";
import { ToolContext, ToolInvocation, ModelProvider, ModelRequest, ModelContext, ModelEvent } from "../src/contracts.js";
import { ToolRouter } from "../src/tools.js";
import { MemoryConversationStore, sessionFromBase } from "../src/conversation.js";
import { InteractiveApprovalGateway } from "../src/application-gateway.js";
import { MockModelProvider } from "../src/adapters.js";
import { DeterministicConversationCompactor } from "../src/compaction.js";
import { PendingApprovalProvider } from "../src/approval-pending.js";
import { AllowAllToolAuthorizationPolicy } from "../src/authorization-mocks.js";

const ctx = (sessionId = "session-a"): ToolContext => ({ traceId: "trace", sessionId, executionId: "execution", signal: new AbortController().signal });
const call = (toolId: string, input: unknown): ToolInvocation => ({ schemaVersion: 1, requestId: `${toolId}-request`, toolId, input: input as never });
async function invoke(provider: TaskToolProvider, toolId: string, input: unknown, session = "session-a") { return provider.invoke(call(toolId, input), ctx(session)); }

describe("task state and verification", () => {
  it("creates, advances ordered steps, and isolates sessions", async () => { const store = new MemoryTaskStore(); const provider = new TaskToolProvider(store); const created = await invoke(provider, "create", { objective: "ALPHA_TASK", constraints: ["no hidden retries"] }); expect(created).toMatchObject({ ok: true, output: { status: "active", version: 1 } }); const task = await store.get("session-a"); const added = await invoke(provider, "update", { version: task!.version, update: { type: "add_step", stepId: "inspect", description: "Inspect contracts" } }); const addedTask = await store.get("session-a"); expect(added).toMatchObject({ ok: true, output: { version: 2 } }); await invoke(provider, "update", { version: addedTask!.version, update: { type: "set_step_status", stepId: "inspect", status: "active" } }); const other = await invoke(provider, "create", { objective: "BETA_TASK" }, "session-b"); expect(other).toMatchObject({ ok: true }); expect((await store.get("session-b"))!.objective).toBe("BETA_TASK"); expect((await provider.invoke(call("get", {}), ctx("session-a"))).output).toMatchObject({ objective: "ALPHA_TASK" }); });
  it("guards completion until all required criteria pass", async () => { const store = new MemoryTaskStore(); const provider = new TaskToolProvider(store); await invoke(provider, "create", { objective: "verify" }); let task = await store.get("session-a"); await invoke(provider, "update", { version: task!.version, update: { type: "add_criterion", criterionId: "tests", description: "Tests pass" } }); task = await store.get("session-a"); await invoke(provider, "update", { version: task!.version, update: { type: "add_criterion", criterionId: "arch", description: "Architecture passes" } }); task = await store.get("session-a"); expect((await invoke(provider, "update", { version: task!.version, update: { type: "complete" } })).ok).toBe(false); task = await store.get("session-a"); await invoke(provider, "update", { version: task!.version, update: { type: "add_evidence", criterionId: "tests", source: "execution", outcome: "pass", summary: "tests passed", executionId: "exec-1", toolCallId: "call-1" } }); task = await store.get("session-a"); await invoke(provider, "update", { version: task!.version, update: { type: "add_evidence", criterionId: "arch", source: "tool", outcome: "fail", summary: "guard failed" } }); task = await store.get("session-a"); expect((await invoke(provider, "update", { version: task!.version, update: { type: "complete" } })).ok).toBe(false); task = await store.get("session-a"); await invoke(provider, "update", { version: task!.version, update: { type: "add_evidence", criterionId: "arch", source: "tool", outcome: "pass", summary: "guard passed" } }); task = await store.get("session-a"); const completed = await invoke(provider, "update", { version: task!.version, update: { type: "complete" } }); expect(completed).toMatchObject({ ok: true, output: { status: "completed" } }); const final = await store.get("session-a"); expect(criterionState(final!, "arch")).toBe("pass"); expect(final!.evidence).toHaveLength(3); });
  it("preserves immutable evidence history and rejects stale updates without mutation", async () => { const store = new MemoryTaskStore(); const provider = new TaskToolProvider(store); await invoke(provider, "create", { objective: "evidence" }); let task = await store.get("session-a"); await invoke(provider, "update", { version: task!.version, update: { type: "add_criterion", criterionId: "tests", description: "Tests pass" } }); task = await store.get("session-a"); await invoke(provider, "update", { version: task!.version, update: { type: "add_evidence", criterionId: "tests", source: "execution", outcome: "fail", summary: "run 1 failed" } }); task = await store.get("session-a"); await invoke(provider, "update", { version: task!.version, update: { type: "add_evidence", criterionId: "tests", source: "execution", outcome: "pass", summary: "run 2 passed" } }); const latest = await store.get("session-a"); expect(latest!.evidence.map((entry) => entry.outcome)).toEqual(["fail", "pass"]); expect(criterionState(latest!, "tests")).toBe("pass"); const stale = await invoke(provider, "update", { version: 1, update: { type: "set_status", status: "blocked" } }); expect(stale.ok).toBe(false); expect((await store.get("session-a"))!.version).toBe(latest!.version); });
  it("survives conversation compaction in the next model control context", async () => { const tasks = new MemoryTaskStore(); const sessionId = "session-c"; await tasks.create(sessionId, "TASK_SENTINEL_42"); const conversations = new MemoryConversationStore(); await conversations.createSession(sessionFromBase({ schemaVersion: 1, id: sessionId, state: "open", createdAt: new Date().toISOString() })); await conversations.commitTurn(sessionId, { messages: [{ role: "user", content: "old one" }, { role: "assistant", content: "old answer" }] }); await conversations.commitTurn(sessionId, { messages: [{ role: "user", content: "old two" }, { role: "assistant", content: "old answer two" }] }); let request: ModelRequest | undefined; const model: ModelProvider = { descriptor: new MockModelProvider("x").descriptor, async *generate(next: ModelRequest, _context: ModelContext): AsyncIterable<ModelEvent> { request = next; yield { type: "delta", text: "done" }; yield { type: "completed" }; } }; const gateway = new InteractiveApprovalGateway(model, new ToolRouter(), new PendingApprovalProvider(), new AllowAllToolAuthorizationPolicy(), { maxSteps: 1, maxToolCalls: 1 }, conversations, { enabled: true, threshold: 1, keepRecentTurns: 1, compactor: new DeterministicConversationCompactor(), taskStore: tasks }); const events = gateway.execute({ type: "SubmitInput", sessionId, input: "continue" }); for await (const _event of events) {} expect(request?.control?.some((message) => message.content.includes("TASK_SENTINEL_42"))).toBe(true); });
});
