import { describe, expect, it } from "vitest";
import { MCPToolProvider, McpConnection, McpToolResult, mcpStdioConfigSchema } from "../src/adapters/tool-mcp.js";
import { JsonValue, ToolContext } from "../src/index.js";
import { ToolRouter } from "../src/tools.js";

const context = (signal = new AbortController().signal, deadline?: number): ToolContext => ({ traceId: "trace", sessionId: "session", executionId: "invocation", signal, deadline });
function connectionFactory(pages: { tools: { name: string; description?: string; inputSchema: JsonValue }[]; nextCursor?: string }[], call: (name: string, input: JsonValue, signal?: AbortSignal) => Promise<McpToolResult> = async (_name, input) => ({ content: [input] })): { connection: McpConnection; get connects(): number; get closes(): number; calls: string[] } {
  let connects = 0; let closes = 0; const calls: string[] = []; return { get connects() { return connects; }, get closes() { return closes; }, calls, connection: { connect: async () => { connects++; }, listTools: async (cursor) => pages[cursor ? 1 : 0]!, callTool: async (name, input, signal) => { calls.push(name); return call(name, input, signal); }, close: async () => { closes++; } } };
}

describe("MCPToolProvider", () => {
  it("validates config, connects once, paginates, and sorts descriptors", async () => {
    expect(mcpStdioConfigSchema.parse({ providerId: "server-a", command: "node" }).providerId).toBe("server-a"); const fixture = connectionFactory([{ tools: [{ name: "zeta", inputSchema: {} }], nextCursor: "next" }, { tools: [{ name: "alpha", description: "a", inputSchema: {} }] }]); const provider = new MCPToolProvider({ providerId: "server-a", command: "node" }, () => fixture.connection); expect((await provider.listTools(context())).map((tool) => tool.id)).toEqual(["alpha", "zeta"]); await provider.listTools(context()); expect(fixture.connects).toBe(1); await provider.close(); expect(fixture.closes).toBe(1);
  });
  it("maps invocation, validates arguments, rejects wrong provider, and maps tool errors", async () => { const fixture = connectionFactory([{ tools: [{ name: "echo", inputSchema: { type: "object", required: ["value"] } }] }], async (name) => name === "fail" ? { content: ["failed"], isError: true } : { content: ["ok"] }); const provider = new MCPToolProvider({ providerId: "server-a", command: "node" }, () => fixture.connection); await provider.listTools(context()); expect(await provider.invoke({ schemaVersion: 1, requestId: "1", toolId: "server-a/echo", input: { value: 1 } }, context())).toMatchObject({ ok: true, output: ["ok"] }); expect((await provider.invoke({ schemaVersion: 1, requestId: "invalid", toolId: "server-a/echo", input: {} }, context())).error?.code).toBe("VALIDATION_FAILED"); expect((await provider.invoke({ schemaVersion: 1, requestId: "2", toolId: "server-b/echo", input: null }, context())).error?.code).toBe("CAPABILITY_UNAVAILABLE"); expect(fixture.calls).toEqual(["echo"]); });
  it("preserves structured results and normalizes cancellation/deadlines", async () => { let rejectCall!: (error: unknown) => void; const fixture = connectionFactory([{ tools: [{ name: "slow", inputSchema: {} }] }], async (_name, _input, signal) => new Promise((_, reject) => { rejectCall = reject; signal?.addEventListener("abort", () => reject(new DOMException("cancelled", "AbortError")), { once: true }); })); const provider = new MCPToolProvider({ providerId: "server-a", command: "node" }, () => fixture.connection); await provider.listTools(context()); const controller = new AbortController(); const pending = provider.invoke({ schemaVersion: 1, requestId: "1", toolId: "server-a/slow", input: {} }, context(controller.signal)); await Promise.resolve(); controller.abort(); rejectCall?.(new DOMException("cancelled", "AbortError")); expect((await pending).error?.code).toBe("CANCELLED"); const timedFixture = connectionFactory([{ tools: [{ name: "slow", inputSchema: {} }] }], async (_name, _input, signal) => new Promise((_, reject) => signal?.addEventListener("abort", () => reject(new DOMException("timeout", "AbortError")), { once: true }))); const timed = new MCPToolProvider({ providerId: "server-b", command: "node" }, () => timedFixture.connection); const timedResult = timed.invoke({ schemaVersion: 1, requestId: "2", toolId: "server-b/slow", input: {} }, context(new AbortController().signal, Date.now() + 5)); expect((await timedResult).error?.code).toBe("TIMEOUT"); });
  it("rejects duplicate tools and cursor cycles", async () => { const duplicate = connectionFactory([{ tools: [{ name: "same", inputSchema: {} }, { name: "same", inputSchema: {} }] }]); await expect(new MCPToolProvider({ providerId: "server-a", command: "node" }, () => duplicate.connection).listTools(context())).rejects.toMatchObject({ error: { code: "TOOL_FAILED" } }); const cycle = connectionFactory([{ tools: [{ name: "same", inputSchema: {} }], nextCursor: "loop" }, { tools: [], nextCursor: "loop" }]); await expect(new MCPToolProvider({ providerId: "server-b", command: "node" }, () => cycle.connection).listTools(context())).rejects.toMatchObject({ error: { code: "TOOL_FAILED" } }); });
});

const live = process.env.RUN_MCP_INTEGRATION_TESTS === "1" ? describe : describe.skip;
live("MCP stdio integration", () => {
  it("connects, discovers, invokes, cancels, times out, and scopes providers", async () => {
    const command = process.execPath; const script = new URL("../dist/tests/mcp-fixture-server.js", import.meta.url).pathname;
    const a = new MCPToolProvider({ providerId: "server-a", command, args: [script] }); const b = new MCPToolProvider({ providerId: "server-b", command, args: [script] });
    const router = new ToolRouter(); await router.register("server-a", a, context()); await router.register("server-b", b, context()); expect(router.listTools().filter((tool) => tool.name === "echo").map((tool) => tool.canonicalId)).toEqual(["server-a/echo", "server-b/echo"]); const add = await router.invoke({ schemaVersion: 1, requestId: "1", toolId: "server-a/add", input: { left: 2, right: 3 } }, context()); expect(add).toEqual({ ok: true, output: { sum: 5 } }); expect((await router.invoke({ schemaVersion: 1, requestId: "2", toolId: "server-b/fail", input: {} }, context())).error?.code).toBe("TOOL_FAILED"); const cancelledController = new AbortController(); const cancelled = router.invoke({ schemaVersion: 1, requestId: "3", toolId: "server-a/slow", input: {} }, context(cancelledController.signal)); await new Promise((resolve) => setTimeout(resolve, 30)); cancelledController.abort(); expect((await cancelled).error?.code).toBe("CANCELLED"); const timed = router.invoke({ schemaVersion: 1, requestId: "4", toolId: "server-b/slow", input: {} }, context(new AbortController().signal, Date.now() + 30)); expect((await timed).error?.code).toBe("TIMEOUT"); await a.close(); await b.close();
  });
});
