import { createHash } from "node:crypto";
import { ProcessRunner, DirectArgvProcessRunner, ProcessRunResult } from "./process-runner.js";
import { failure } from "./contracts.js";

export interface ImageIdentity { readonly repository: string; readonly tag: string; readonly reference: string; readonly sourceRevision: string; readonly digest?: string; readonly latestReference?: string }
export interface ImageAdapter { build(sourceRevision: string, tag: string): Promise<ImageIdentity>; push(identity: ImageIdentity): Promise<ImageIdentity> }
export interface DockerImageConfig { readonly workspaceRoot: string; readonly imageRepository: string; readonly registry: string; readonly executable?: string; readonly maxOutputBytes?: number; readonly environment?: Readonly<Record<string, string>> }
export class DockerImageAdapter implements ImageAdapter {
  private readonly executable: string; private readonly maxOutputBytes: number; private readonly environment: Readonly<Record<string, string>>;
  constructor(private readonly config: DockerImageConfig, private readonly runner: ProcessRunner = new DirectArgvProcessRunner()) { this.executable = config.executable ?? "docker"; this.maxOutputBytes = config.maxOutputBytes ?? 262144; this.environment = { PATH: process.env.PATH ?? "", ...config.environment }; }
  async build(sourceRevision: string, tag: string): Promise<ImageIdentity> { if (!/^[a-zA-Z0-9._-]+$/.test(tag)) throw failure("VALIDATION_FAILED", "Image tag is invalid."); const repository = `${this.config.registry.replace(/\/$/, "")}/${this.config.imageRepository.replace(/^\//, "")}`; const reference = `${repository}:${tag}`; const result = await this.run(["build", "--build-arg", `GIT_COMMIT=${sourceRevision}`, "--build-arg", `BUILD_ID=${sourceRevision.slice(0, 12)}`, "--label", `org.opencontainers.image.revision=${sourceRevision}`, "-t", reference, this.config.workspaceRoot]); ensure(result, "Docker image build failed."); return { repository, tag, reference, sourceRevision }; }
  async push(identity: ImageIdentity): Promise<ImageIdentity> { const pushed = await this.run(["push", identity.reference]); ensure(pushed, "Docker image push failed."); const latest = `${identity.repository}:latest`; const tagged = await this.run(["tag", identity.reference, latest]); ensure(tagged, "Docker latest tag failed."); const latestPush = await this.run(["push", latest]); ensure(latestPush, "Docker latest push failed."); const digest = digestFrom(pushed.stdout + pushed.stderr + latestPush.stdout + latestPush.stderr); return { ...identity, latestReference: latest, ...(digest ? { digest } : {}) }; }
  private async run(args: readonly string[]): Promise<ProcessRunResult> { return this.runner.run({ executable: this.executable, args, cwd: this.config.workspaceRoot, environment: this.environment, signal: new AbortController().signal, maxStdoutBytes: this.maxOutputBytes, maxStderrBytes: this.maxOutputBytes }); }
}

export interface DeploymentAttempt { readonly id: string; readonly target: string; readonly sourceRevision: string; readonly imageReference: string; readonly startedAt: string; readonly status: "triggered" | "failed"; readonly exitCode?: number; readonly stdout: string; readonly stderr: string }
export interface DeploymentAdapter { deploy(input: { readonly sourceRevision: string; readonly imageReference: string; readonly previousRevision?: string; readonly previousImageReference?: string }): Promise<DeploymentAttempt> }
export interface OneShotSshConfig { readonly target?: string; readonly executable?: string; readonly maxOutputBytes?: number; readonly cwd?: string }
/** Deliberately passes no remote command. The deploy account owns the procedure. */
export class OneShotSshDeployment implements DeploymentAdapter {
  constructor(private readonly config: OneShotSshConfig = {}, private readonly runner: ProcessRunner = new DirectArgvProcessRunner()) {}
  async deploy(input: { readonly sourceRevision: string; readonly imageReference: string; readonly previousRevision?: string; readonly previousImageReference?: string }): Promise<DeploymentAttempt> { const startedAt = new Date().toISOString(); const result = await this.runner.run({ executable: this.config.executable ?? "ssh", args: [this.config.target ?? "deploy_porta@nas"], cwd: this.config.cwd ?? process.cwd(), environment: { PATH: process.env.PATH ?? "" }, signal: new AbortController().signal, maxStdoutBytes: this.config.maxOutputBytes ?? 262144, maxStderrBytes: this.config.maxOutputBytes ?? 262144 }); const id = `deployment-${createHash("sha256").update(`${startedAt}\0${input.sourceRevision}\0${input.imageReference}`).digest("hex").slice(0, 16)}`; return { id, target: this.config.target ?? "deploy_porta@nas", sourceRevision: input.sourceRevision, imageReference: input.imageReference, startedAt, status: result.status === "completed" && result.exitCode === 0 ? "triggered" : "failed", ...(result.exitCode === undefined ? {} : { exitCode: result.exitCode }), stdout: result.stdout, stderr: result.stderr }; }
}

export interface DeploymentHealth { readonly ready: boolean; readonly correctRevision: boolean; readonly taskStateAvailable: boolean; readonly observedRevision?: string; readonly message?: string }
export interface DeploymentHealthOptions { readonly headers?: Readonly<Record<string, string>>; readonly taskId?: string }
export async function qualifyDeployment(endpoint: string, expectedRevision: string, fetcher: typeof fetch = fetch, options: DeploymentHealthOptions = {}): Promise<DeploymentHealth> { try { const init = { headers: options.headers }; const readyResponse = await fetcher(new URL("/ready", endpoint), init); const versionResponse = await fetcher(new URL("/version", endpoint), init); const ready = readyResponse.ok; const version = versionResponse.ok ? await versionResponse.json() as { commit?: string } : {}; const correctRevision = version.commit === expectedRevision; let taskStateAvailable = false; try { const tasks = await fetcher(new URL("/api/tasks", endpoint), init); if (tasks.ok && options.taskId) { const payload = await tasks.json() as { tasks?: readonly { id?: string }[] }; taskStateAvailable = payload.tasks?.some((entry) => entry.id === options.taskId) ?? false; } else taskStateAvailable = tasks.ok; } catch {} return { ready, correctRevision, taskStateAvailable, ...(version.commit ? { observedRevision: version.commit } : {}), ...(!ready ? { message: "Porta readiness failed." } : !correctRevision ? { message: "Running revision does not match the deployed revision." } : !taskStateAvailable ? { message: "Task API is unavailable." } : {}) }; } catch (error) { return { ready: false, correctRevision: false, taskStateAvailable: false, message: error instanceof Error ? error.message : "Deployment health check failed." }; } }
function ensure(result: ProcessRunResult, message: string): void { if (result.status !== "completed") throw failure(result.status === "timed-out" ? "TIMEOUT" : "CANCELLED", message, result.status === "timed-out"); if (result.exitCode !== 0) throw failure("RUNTIME_FAILED", `${message} ${result.stderr.slice(-2000)}`); }
function digestFrom(value: string): string | undefined { const match = value.match(/(?:digest:|@)(sha256:[a-f0-9]{64})/i); return match?.[1]; }
