import { promises as fs } from "node:fs";
import { z } from "zod";
import { ExecutionPolicy, JsonValue, RuntimeHost, SandboxProvider, ToolContext, ToolDescriptor, ToolInvocation, ToolProvider, ToolResult, failure } from "./contracts.js";
import { RuntimeCoordinator } from "./runtime.js";
import { WorkspaceBoundary } from "./workspace.js";

export interface ExecutionProviderConfig { workspaceRoot: string; allowedCommands: readonly string[]; defaultTimeoutMs: number; maxStdoutBytes: number; maxStderrBytes: number; policy: ExecutionPolicy; environment?: Readonly<Record<string, string>>; allowedEnvironmentKeys?: readonly string[] }
const inputSchema = z.object({ command: z.string().min(1), args: z.array(z.string()).default([]), cwd: z.string().min(1).optional(), timeoutMs: z.number().int().positive().optional(), environment: z.record(z.string()).optional() }).strict();

export class ExecutionToolProvider implements ToolProvider {
  readonly providerId = "execution";
  private readonly boundary: WorkspaceBoundary;
  private readonly coordinator: RuntimeCoordinator;
  constructor(private readonly runtime: RuntimeHost, private readonly sandbox: SandboxProvider, private readonly config: ExecutionProviderConfig) { this.boundary = new WorkspaceBoundary(config.workspaceRoot); this.coordinator = new RuntimeCoordinator(runtime, sandbox); }
  async listTools(_context: ToolContext): Promise<readonly ToolDescriptor[]> { return [{ id: "run", name: "execution/run", version: "1", description: "Run one explicitly structured workspace command using command plus argv args. No shell is used. Inspect exitCode, stdout, and stderr; a nonzero exit is a normal process result.", inputSchema: { type: "object", required: ["command"], properties: { command: { type: "string" }, args: { type: "array", items: { type: "string" } }, cwd: { type: "string" }, timeoutMs: { type: "integer" }, environment: { type: "object" } } } }]; }
  async invoke(request: ToolInvocation, context: ToolContext): Promise<ToolResult> {
    const parsed = inputSchema.safeParse(request.input); if (!parsed.success) return invalid(parsed.error.issues); const input = parsed.data;
    if (!this.config.allowedCommands.includes(input.command)) return { ok: false, error: failure("POLICY_VIOLATION", `Command '${input.command}' is not allowed.`).error };
    if (context.signal.aborted) return { ok: false, error: failure("CANCELLED", "Execution was cancelled before it started.").error }; if (context.deadline !== undefined && context.deadline <= Date.now()) return { ok: false, error: failure("TIMEOUT", "Execution deadline has expired.", true).error }; let cwd: string; try { cwd = input.cwd ? await this.boundary.resolveRead(input.cwd) : this.boundary.root; const cwdStat = await fs.stat(cwd); if (!cwdStat.isDirectory()) return { ok: false, error: failure("VALIDATION_FAILED", "Execution cwd must be a directory.").error }; } catch (error) { return { ok: false, error: error instanceof Error && "error" in error ? (error as { error: import("./contracts.js").HarnessError }).error : failure("VALIDATION_FAILED", "Execution cwd is invalid.").error }; }
    const environment = this.buildEnvironment(input.environment); const timeout = Math.min(input.timeoutMs ?? this.config.defaultTimeoutMs, this.config.defaultTimeoutMs); const deadline = context.deadline === undefined ? Date.now() + timeout : Math.min(context.deadline, Date.now() + timeout); const executionContext = { ...context, deadline };
    let execution; try { execution = await this.coordinator.createExecution({ schemaVersion: 1, executable: input.command, args: input.args, workingDirectory: cwd, environment, timeoutMs: timeout, policy: this.config.policy }, executionContext); } catch (error) { return { ok: false, error: asError(error, "RUNTIME_FAILED", "Execution could not be started.") }; }
    const stdout = new BoundedText(this.config.maxStdoutBytes); const stderr = new BoundedText(this.config.maxStderrBytes); try { for await (const event of execution.events()) { if (event.type === "stdout") stdout.append(event.data); else if (event.type === "stderr") stderr.append(event.data); } const result = await execution.result(); if (result.status === "failed") return { ok: false, error: result.error ?? failure("RUNTIME_FAILED", "Execution failed.").error }; return { ok: true, output: { status: result.status, ...(result.exitCode === undefined ? {} : { exitCode: result.exitCode }), stdout: stdout.value(), stderr: stderr.value(), stdoutTruncated: stdout.truncated, stderrTruncated: stderr.truncated, timedOut: result.status === "timed-out", cancelled: result.status === "cancelled", cwd, command: input.command, args: input.args, runtime: this.runtime.descriptor.id, sandbox: { provider: this.sandbox.descriptor.id, policy: this.config.policy, enforcement: this.sandbox.capabilities } } as unknown as JsonValue }; } catch (error) { await execution.cancel().catch(() => undefined); return { ok: false, error: asError(error, "RUNTIME_FAILED", "Execution output could not be collected.") }; }
  }
  private buildEnvironment(requested?: Readonly<Record<string, string>>): Record<string, string> { const allowed = new Set(this.config.allowedEnvironmentKeys ?? ["PATH"]); const environment: Record<string, string> = { ...(this.config.environment ?? {}) }; for (const key of allowed) if (process.env[key] !== undefined && environment[key] === undefined) environment[key] = process.env[key]!; for (const [key, value] of Object.entries(requested ?? {})) if (allowed.has(key)) environment[key] = value; return environment; }
}
class BoundedText { private head = ""; private tail = ""; truncated = false; constructor(private readonly max: number) {} append(value: string) { if (this.truncated) { this.tail = `${this.tail}${value}`.slice(-Math.floor(this.max / 2)); return; } const combined = this.head + value; if (Buffer.byteLength(combined) <= this.max) { this.head = combined; return; } const half = Math.floor(this.max / 2); this.head = combined.slice(0, half); this.tail = combined.slice(-half); this.truncated = true; } value(): string { return this.truncated ? `${this.head}\n...[truncated]...\n${this.tail}` : this.head; } }
function invalid(issues: unknown): ToolResult { return { ok: false, error: failure("VALIDATION_FAILED", "Execution arguments are invalid.", false, { issues }).error }; }
function asError(error: unknown, code: "RUNTIME_FAILED", message: string) { return error instanceof Error && "error" in error ? (error as { error: import("./contracts.js").HarnessError }).error : failure(code, error instanceof Error ? error.message : message).error; }
