import { promises as fs } from "node:fs";
import { isAbsolute, relative, resolve } from "node:path";
import { z } from "zod";
import { HarnessFailure, JsonValue, ToolContext, ToolDescriptor, ToolInvocation, ToolProvider, ToolResult, failure } from "./contracts.js";
import { DirectArgvProcessRunner, ProcessRunner, ProcessRunResult } from "./process-runner.js";
import { WorkspaceBoundary } from "./workspace.js";

export interface GitOperationContext { readonly signal: AbortSignal; readonly deadline?: number }
export interface GitStatusResult { readonly branch?: string; readonly detached: boolean; readonly clean: boolean; readonly staged: readonly string[]; readonly unstaged: readonly string[]; readonly untracked: readonly string[]; readonly conflicts: readonly string[]; readonly truncated: boolean }
export interface GitDiffResult { readonly mode: "working-tree" | "staged"; readonly path?: string; readonly filesChanged: number; readonly insertions: number; readonly deletions: number; readonly patch: string; readonly truncated: boolean }
export interface GitShowResult { readonly revision: string; readonly hash?: string; readonly author?: string; readonly email?: string; readonly timestamp?: string; readonly subject?: string; readonly patch: string; readonly truncated: boolean }
export interface GitLogEntry { readonly hash: string; readonly author?: string; readonly email?: string; readonly timestamp?: string; readonly subject: string }
export interface GitLogResult { readonly entries: readonly GitLogEntry[]; readonly truncated: boolean }
export interface GitBackend { readonly repositoryRoot: string; available?(): Promise<boolean>; status(context: GitOperationContext): Promise<GitStatusResult>; diff(input: { readonly staged?: boolean; readonly path?: string; readonly contextLines?: number }, context: GitOperationContext): Promise<GitDiffResult>; show(input: { readonly revision: string; readonly path?: string }, context: GitOperationContext): Promise<GitShowResult>; log(input: { readonly limit?: number; readonly path?: string }, context: GitOperationContext): Promise<GitLogResult> }

export interface CliGitConfig { readonly root: string; readonly executable?: string; readonly maxStatusEntries?: number; readonly maxDiffBytes?: number; readonly maxShowBytes?: number; readonly maxLogEntries?: number }
export class CliGitBackend implements GitBackend {
  readonly repositoryRoot: string; private readonly boundary: WorkspaceBoundary; private readonly executable: string; private readonly runner: ProcessRunner; private readonly maxStatusEntries: number; private readonly maxDiffBytes: number; private readonly maxShowBytes: number; private readonly maxLogEntries: number; private ready?: boolean;
  constructor(config: CliGitConfig, runner: ProcessRunner = new DirectArgvProcessRunner()) { this.boundary = new WorkspaceBoundary(config.root); this.repositoryRoot = this.boundary.root; this.executable = config.executable ?? "git"; this.runner = runner; this.maxStatusEntries = config.maxStatusEntries ?? 1000; this.maxDiffBytes = config.maxDiffBytes ?? 262144; this.maxShowBytes = config.maxShowBytes ?? 262144; this.maxLogEntries = config.maxLogEntries ?? 20; }
  async available(): Promise<boolean> { if (this.ready !== undefined) return this.ready; try { const version = await this.run(["--version"], { signal: new AbortController().signal }); if (version.exitCode !== 0) return this.ready = false; const root = await this.run(["rev-parse", "--show-toplevel"], { signal: new AbortController().signal }); if (root.exitCode !== 0) return this.ready = false; const discovered = await fs.realpath(root.stdout.trim()); return this.ready = discovered === this.repositoryRoot; } catch { return this.ready = false; } }
  async status(context: GitOperationContext): Promise<GitStatusResult> { const result = await this.run(["status", "--porcelain=v1", "-z", "-b", "--untracked-files=all"], context); ensureSuccess(result, "Git status failed."); const tokens = result.stdout.split("\0").filter(Boolean); const first = tokens.shift() ?? "## HEAD (no branch)"; const detached = first.includes("HEAD (no branch)"); const branch = detached ? undefined : parseBranch(first); const staged: string[] = []; const unstaged: string[] = []; const untracked: string[] = []; const conflicts: string[] = []; for (let index = 0; index < tokens.length; index++) { const token = tokens[index]!; const code = token.slice(0, 2); const path = token.slice(3); const pathValue = path.includes(" -> ") ? path.slice(path.lastIndexOf(" -> ") + 4) : path; if (code === "??") untracked.push(pathValue); else { if (code[0] !== " ") staged.push(pathValue); if (code[1] !== " ") unstaged.push(pathValue); if (code.includes("U") || code === "AA" || code === "DD") conflicts.push(pathValue); if (code[0] === "R" && tokens[index + 1] && !tokens[index + 1]!.startsWith(" ")) index++; } } const truncated = tokens.length > this.maxStatusEntries || result.stdoutTruncated; return { ...(branch ? { branch } : {}), detached, clean: !staged.length && !unstaged.length && !untracked.length && !conflicts.length, staged: staged.slice(0, this.maxStatusEntries), unstaged: unstaged.slice(0, this.maxStatusEntries), untracked: untracked.slice(0, this.maxStatusEntries), conflicts: conflicts.slice(0, this.maxStatusEntries), truncated }; }
  async diff(input: { readonly staged?: boolean; readonly path?: string; readonly contextLines?: number }, context: GitOperationContext): Promise<GitDiffResult> { const path = input.path ? await this.pathSpec(input.path) : undefined; const args = ["diff", "--no-ext-diff", "--no-textconv", "--no-color", `--unified=${Math.min(Math.max(input.contextLines ?? 3, 0), 100)}`]; if (input.staged) args.push("--cached"); if (path) args.push("--", relative(this.repositoryRoot, path)); const result = await this.run(args, context, this.maxDiffBytes); ensureSuccess(result, "Git diff failed."); return { mode: input.staged ? "staged" : "working-tree", ...(input.path ? { path: input.path } : {}), filesChanged: (result.stdout.match(/^diff --git /gm) ?? []).length, insertions: (result.stdout.match(/^\+(?!\+\+)/gm) ?? []).length, deletions: (result.stdout.match(/^(?!--)-/gm) ?? []).length, patch: result.stdout, truncated: result.stdoutTruncated }; }
  async show(input: { readonly revision: string; readonly path?: string }, context: GitOperationContext): Promise<GitShowResult> { validateRevision(input.revision); const path = input.path ? await this.pathSpec(input.path) : undefined; const args = ["show", "--no-ext-diff", "--no-textconv", "--no-color", "--format=%H%x00%an%x00%ae%x00%cI%x00%s%x00", input.revision]; if (path) args.push("--", relative(this.repositoryRoot, path)); const result = await this.run(args, context, this.maxShowBytes); ensureSuccess(result, "Git show failed."); const fields = result.stdout.split("\0"); return { revision: input.revision, hash: fields[0] || undefined, author: fields[1] || undefined, email: fields[2] || undefined, timestamp: fields[3] || undefined, subject: fields[4]?.trimEnd() || undefined, patch: fields.slice(5).join("\0"), truncated: result.stdoutTruncated }; }
  async log(input: { readonly limit?: number; readonly path?: string }, context: GitOperationContext): Promise<GitLogResult> { const limit = Math.min(Math.max(input.limit ?? 20, 1), this.maxLogEntries); const path = input.path ? await this.pathSpec(input.path) : undefined; const args = ["log", `-n${limit}`, "--format=%x1e%H%x00%an%x00%ae%x00%cI%x00%s"]; if (path) args.push("--", relative(this.repositoryRoot, path)); const result = await this.run(args, context, this.maxShowBytes); if (result.exitCode !== 0 && result.stderr.includes("does not have any commits")) return { entries: [], truncated: false }; ensureSuccess(result, "Git log failed."); const entries = result.stdout.split("\x1e").filter(Boolean).map((record) => { const fields = record.split("\0"); return { hash: fields[0] ?? "", author: fields[1] || undefined, email: fields[2] || undefined, timestamp: fields[3] || undefined, subject: fields[4]?.trimEnd() ?? "" }; }); return { entries, truncated: result.stdoutTruncated }; }
  private async pathSpec(requested: string): Promise<string> { if (!requested || isAbsolute(requested)) throw failure("CAPABILITY_UNAVAILABLE", "Git paths must be relative to the configured workspace."); const candidate = resolve(this.repositoryRoot, requested); const path = relative(this.repositoryRoot, candidate); if (path === ".." || path.startsWith(".." + requireSep()) || isAbsolute(path)) throw failure("CAPABILITY_UNAVAILABLE", "Git path is outside the configured workspace."); try { const target = await fs.realpath(candidate); if (relative(this.repositoryRoot, target).startsWith("..")) throw failure("CAPABILITY_UNAVAILABLE", "Git path resolves outside the configured workspace."); return target; } catch (error) { if ((error as NodeJS.ErrnoException)?.code === "ENOENT") return candidate; throw error; } }
  private run(args: readonly string[], context: GitOperationContext, maxBytes = 65536): Promise<ProcessRunResult> { return this.runner.run({ executable: this.executable, args, cwd: this.repositoryRoot, environment: { PATH: process.env.PATH ?? "", GIT_OPTIONAL_LOCKS: "0", GIT_TERMINAL_PROMPT: "0", LC_ALL: "C" }, signal: context.signal, deadline: context.deadline, maxStdoutBytes: maxBytes, maxStderrBytes: 16384 }); }
}
function requireSep() { return process.platform === "win32" ? "\\" : "/"; }
function parseBranch(line: string): string | undefined { const value = line.slice(3).split("...")[0]; return value && value !== "(no branch)" ? value : undefined; }
function validateRevision(revision: string) { if (!revision || revision.length > 200 || revision.startsWith("-") || revision.includes("\0") || revision.includes("\n")) throw failure("VALIDATION_FAILED", "Git revision is invalid."); }
function ensureSuccess(result: ProcessRunResult, message: string) { if (result.status !== "completed") throw failure(result.status === "timed-out" ? "TIMEOUT" : "CANCELLED", "Git operation did not complete.", result.status === "timed-out"); if (result.exitCode !== 0) { const detail = result.stderr.slice(-2000); throw failure(result.stderr.includes("not a git repository") ? "CAPABILITY_UNAVAILABLE" : "TOOL_FAILED", detail ? `${message} ${detail}` : message, false); } }

const statusSchema = z.object({}).strict();
const diffSchema = z.object({ staged: z.boolean().optional(), path: z.string().min(1).optional(), contextLines: z.number().int().min(0).max(100).optional() }).strict();
const showSchema = z.object({ revision: z.string().min(1).max(200), path: z.string().min(1).optional() }).strict();
const logSchema = z.object({ limit: z.number().int().positive().max(100).optional(), path: z.string().min(1).optional() }).strict();
export class GitToolProvider implements ToolProvider {
  readonly providerId = "git";
  constructor(private readonly backend: GitBackend) {}
  async listTools(_context: ToolContext): Promise<readonly ToolDescriptor[]> { return [
    { id: "status", name: "git/status", version: "1", description: "Inspect the configured local repository worktree without mutation or network access.", inputSchema: { type: "object", properties: {} } },
    { id: "diff", name: "git/diff", version: "1", description: "Inspect bounded working-tree or staged changes.", inputSchema: { type: "object", properties: { staged: { type: "boolean" }, path: { type: "string" }, contextLines: { type: "integer" } } } },
    { id: "show", name: "git/show", version: "1", description: "Inspect one bounded local revision and optional path.", inputSchema: { type: "object", required: ["revision"], properties: { revision: { type: "string" }, path: { type: "string" } } } },
    { id: "log", name: "git/log", version: "1", description: "Inspect bounded local commit history.", inputSchema: { type: "object", properties: { limit: { type: "integer" }, path: { type: "string" } } } },
  ]; }
  async invoke(request: ToolInvocation, context: ToolContext): Promise<ToolResult> { try { if (request.toolId === "status") { const parsed = statusSchema.safeParse(request.input); if (!parsed.success) return invalid(parsed.error.issues); return { ok: true, output: await this.backend.status(context) as unknown as JsonValue }; } if (request.toolId === "diff") { const parsed = diffSchema.safeParse(request.input); if (!parsed.success) return invalid(parsed.error.issues); return { ok: true, output: await this.backend.diff(parsed.data, context) as unknown as JsonValue }; } if (request.toolId === "show") { const parsed = showSchema.safeParse(request.input); if (!parsed.success) return invalid(parsed.error.issues); return { ok: true, output: await this.backend.show(parsed.data, context) as unknown as JsonValue }; } if (request.toolId === "log") { const parsed = logSchema.safeParse(request.input); if (!parsed.success) return invalid(parsed.error.issues); return { ok: true, output: await this.backend.log(parsed.data, context) as unknown as JsonValue }; } return { ok: false, error: failure("CAPABILITY_UNAVAILABLE", `Git tool '${request.toolId}' is unavailable.`).error }; } catch (error) { return { ok: false, error: error instanceof HarnessFailure ? error.error : failure("TOOL_FAILED", error instanceof Error ? error.message : "Git operation failed.").error }; } }
}
function invalid(issues: unknown): ToolResult { return { ok: false, error: failure("VALIDATION_FAILED", "Git arguments are invalid.", false, { issues }).error }; }
