import { createHash, createPrivateKey, createPublicKey, generateKeyPairSync, randomBytes, sign, verify } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
export interface PublicIdentity { identity: string; publicKey: string; algorithm: "ed25519" }
export interface AllowedIdentity extends PublicIdentity { displayName: string; enabled: boolean; createdAt: string; lastSeenAt?: string }
export interface LoginChallenge { challengeId: string; nonce: string; issuedAt: string; expiresAt: string; serverIdentity: PublicIdentity }
const DOMAIN = "porta-login-v1";
export function canonicalLoginPayload(challenge: LoginChallenge, clientIdentity: string): Buffer { return Buffer.from([DOMAIN, challenge.challengeId, challenge.nonce, challenge.serverIdentity.identity, clientIdentity, challenge.issuedAt, challenge.expiresAt].map((value) => `${value.length}:${value}`).join("|")); }
export class InstanceIdentityStore {
  readonly public: PublicIdentity; private readonly privateKey: ReturnType<typeof createPrivateKey>; private allowed: AllowedIdentity[];
  constructor(private readonly directory: string) { mkdirSync(directory, { recursive: true, mode: 0o700 }); const privatePath = join(directory, "identity.ed25519.pem"); const publicPath = join(directory, "identity.ed25519.pub"); if (existsSync(privatePath) && existsSync(publicPath)) { this.privateKey = createPrivateKey(readFileSync(privatePath)); this.public = publicFromPem(readFileSync(publicPath, "utf8")); } else { const pair = generateKeyPairSync("ed25519"); writeFileSync(privatePath, pair.privateKey.export({ type: "pkcs8", format: "pem" }), { mode: 0o600 }); writeFileSync(publicPath, pair.publicKey.export({ type: "spki", format: "pem" }), { mode: 0o644 }); try { chmodSync(privatePath, 0o600); } catch {} this.privateKey = pair.privateKey; this.public = publicFromPem(pair.publicKey.export({ type: "spki", format: "pem" }).toString()); } const allowedPath = join(directory, "allowed-identities.json"); this.allowed = existsSync(allowedPath) ? JSON.parse(readFileSync(allowedPath, "utf8")) as AllowedIdentity[] : []; }
  listAllowed(): readonly AllowedIdentity[] { return this.allowed.map((entry) => ({ ...entry })); }
  isAllowed(identity: string): boolean { return this.allowed.some((entry) => entry.identity === identity && entry.enabled); }
  allow(identity: PublicIdentity, displayName: string): void { const canonical = publicFromPem(identity.publicKey); if (canonical.identity !== identity.identity || canonical.algorithm !== identity.algorithm) throw new Error("IDENTITY_PUBLIC_KEY_MISMATCH"); this.allowed = [...this.allowed.filter((entry) => entry.identity !== identity.identity), { ...canonical, displayName, enabled: true, createdAt: new Date().toISOString() }]; this.persistAllowed(); }
  setEnabled(identity: string, enabled: boolean): void { const entry = this.allowed.find((item) => item.identity === identity); if (entry) { entry.enabled = enabled; this.persistAllowed(); } }
  remove(identity: string): void { this.allowed = this.allowed.filter((item) => item.identity !== identity); this.persistAllowed(); }
  revoke(identity: string): void { this.setEnabled(identity, false); }
  authenticate(identity: string, signature: string, challenge: LoginChallenge): boolean { const entry = this.allowed.find((item) => item.identity === identity); if (!entry?.enabled || !verify(null, canonicalLoginPayload(challenge, identity), createPublicKey(entry.publicKey), Buffer.from(signature, "base64url"))) return false; entry.lastSeenAt = new Date().toISOString(); this.persistAllowed(); return true; }
  sign(challenge: LoginChallenge): string { return sign(null, canonicalLoginPayload(challenge, this.public.identity), this.privateKey).toString("base64url"); }
  private persistAllowed(): void { writeFileSync(join(this.directory, "allowed-identities.json"), JSON.stringify(this.allowed, null, 2) + "\n", { mode: 0o600 }); }
}
export class LoginService { private readonly challenges = new Map<string, LoginChallenge>(); private readonly tokens = new Map<string, { identity: string; expiresAt: number }>(); constructor(readonly identity: InstanceIdentityStore, private readonly now: () => number = Date.now) {}
  challenge(): LoginChallenge { this.cleanup(); const issued = this.now(); const challenge: LoginChallenge = { challengeId: randomBytes(24).toString("base64url"), nonce: randomBytes(32).toString("base64url"), issuedAt: new Date(issued).toISOString(), expiresAt: new Date(issued + 300_000).toISOString(), serverIdentity: this.identity.public }; this.challenges.set(challenge.challengeId, challenge); return challenge; }
  verifyUntrusted(input: { challengeId: string; identity: string; signature: string }, publicIdentity: PublicIdentity): boolean { this.cleanup(); const challenge = this.challenges.get(input.challengeId); this.challenges.delete(input.challengeId); if (!challenge || this.now() >= Date.parse(challenge.expiresAt) || publicIdentity.identity !== input.identity) return false; try { return verify(null, canonicalLoginPayload(challenge, input.identity), createPublicKey(publicIdentity.publicKey), Buffer.from(input.signature, "base64url")); } catch { return false; } }
  login(input: { challengeId: string; identity: string; signature: string }): { token: string; expiresAt: string; identity: string } { this.cleanup(); const challenge = this.challenges.get(input.challengeId); if (!challenge) throw new Error("LOGIN_CHALLENGE_UNKNOWN"); this.challenges.delete(input.challengeId); if (this.now() >= Date.parse(challenge.expiresAt)) throw new Error("LOGIN_CHALLENGE_EXPIRED"); if (!this.identity.authenticate(input.identity, input.signature, challenge)) throw new Error("SIGNATURE_INVALID"); const expires = this.now() + 8 * 60 * 60 * 1000; const token = randomBytes(32).toString("base64url"); this.tokens.set(token, { identity: input.identity, expiresAt: expires }); return { token, expiresAt: new Date(expires).toISOString(), identity: input.identity }; }
  authenticateToken(token: string): string | undefined { const entry = this.tokens.get(token); if (!entry || entry.expiresAt <= this.now() || !this.identity.isAllowed(entry.identity)) { this.tokens.delete(token); return undefined; } return entry.identity; }
  private cleanup(): void { const now = this.now(); for (const [id, challenge] of this.challenges) if (Date.parse(challenge.expiresAt) <= now) this.challenges.delete(id); for (const [token, entry] of this.tokens) if (entry.expiresAt <= now) this.tokens.delete(token); }
}
function publicFromPem(pem: string): PublicIdentity { const key = createPublicKey(pem); const der = key.export({ type: "spki", format: "der" }); const fingerprint = createHash("sha256").update(der).digest("hex"); return { identity: `porta:ed25519:${fingerprint}`, publicKey: pem, algorithm: "ed25519" }; }
