import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { createRequire } from "node:module";
import type { DatabaseSync } from "node:sqlite";
import { z } from "zod";
import { ConversationBudget, ConversationSession, ConversationSnapshot, ConversationStore, ConversationTurn, HarnessFailure, Session, modelToolCallSchema, modelToolResultSchema } from "./contracts.js";
import { ScratchpadEntry, ScratchpadMetadata, ScratchpadStore } from "./scratchpad.js";
import { MemoryTaskStore, Task, TaskStore, TaskUpdate, applyTaskUpdate } from "./task.js";
import { failure } from "./contracts.js";

export interface SqlitePersistence { readonly database: DatabaseSync; readonly conversations: ConversationStore; readonly scratchpad: ScratchpadStore; readonly tasks: TaskStore; close(): void }
const messageSchema = z.union([z.object({ role: z.literal("user"), content: z.string() }).strict(), z.object({ role: z.literal("assistant"), content: z.string().optional(), toolCalls: z.array(modelToolCallSchema).optional() }).strict(), z.object({ role: z.literal("tool"), toolCallId: z.string(), toolId: z.string(), result: modelToolResultSchema }).strict()]);
const taskSchema = z.object({ id: z.string(), sessionId: z.string(), objective: z.string(), constraints: z.array(z.string()), status: z.enum(["pending", "active", "blocked", "completed", "failed", "cancelled"]), steps: z.array(z.object({ id: z.string(), description: z.string(), status: z.enum(["pending", "active", "completed", "blocked", "skipped"]) }).strict()), criteria: z.array(z.object({ id: z.string(), description: z.string(), required: z.boolean() }).strict()), evidence: z.array(z.object({ id: z.string(), criterionId: z.string(), source: z.enum(["execution", "filesystem", "tool", "manual"]), outcome: z.enum(["pass", "fail", "inconclusive"]), summary: z.string(), executionId: z.string().optional(), toolCallId: z.string().optional(), recordedAt: z.string() }).strict()), version: z.number().int().positive(), createdAt: z.string(), updatedAt: z.string() }).strict();

export async function openSqlitePersistence(path: string, budget: ConversationBudget = {}): Promise<SqlitePersistence> { try { await mkdir(dirname(resolve(path)), { recursive: true }); const sqlite = createRequire(import.meta.url)("node:sqlite") as typeof import("node:sqlite"); const database = new sqlite.DatabaseSync(resolve(path), { timeout: 5000 }); migrate(database); return { database, conversations: new SqliteConversationStore(database, budget), scratchpad: new SqliteScratchpadStore(database), tasks: new SqliteTaskStore(database), close: () => database.close() }; } catch (error) { if (error instanceof HarnessFailure) throw error; throw failure("STORAGE_FAILED", error instanceof Error ? error.message : "SQLite database could not be opened."); } }

function migrate(database: DatabaseSync): void { database.exec("PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL; CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL); "); const rows = database.prepare("SELECT version FROM schema_migrations ORDER BY version DESC LIMIT 1").all() as Array<{ version: number }>; const current = rows[0]?.version ?? 0; if (current > 1) throw failure("STORAGE_FAILED", `Unsupported persistence schema version '${current}'.`); if (current === 1) return; database.exec("BEGIN IMMEDIATE; CREATE TABLE sessions (id TEXT PRIMARY KEY, state TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE conversation_turns (session_id TEXT NOT NULL REFERENCES sessions(id), turn_index INTEGER NOT NULL, messages_json TEXT NOT NULL, PRIMARY KEY (session_id, turn_index)); CREATE TABLE scratchpad_entries (session_id TEXT NOT NULL, key TEXT NOT NULL, content TEXT NOT NULL, bytes INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY (session_id, key), FOREIGN KEY (session_id) REFERENCES sessions(id)); CREATE TABLE tasks (session_id TEXT PRIMARY KEY REFERENCES sessions(id), task_id TEXT NOT NULL UNIQUE, version INTEGER NOT NULL, payload_json TEXT NOT NULL, updated_at TEXT NOT NULL); INSERT INTO schema_migrations(version, applied_at) VALUES (1, datetime('now')); COMMIT;"); }
function transaction(database: DatabaseSync, operation: () => void): void { database.exec("BEGIN IMMEDIATE;"); try { operation(); database.exec("COMMIT;"); } catch (error) { try { database.exec("ROLLBACK;"); } catch {} throw error; } }
function storageError(error: unknown): HarnessFailure { return error instanceof HarnessFailure ? error : failure("STORAGE_FAILED", error instanceof Error ? error.message : "Persistent state operation failed."); }
function validatedMessages(value: unknown): ConversationTurn["messages"] { const parsed = z.array(messageSchema).safeParse(value); if (!parsed.success) throw failure("STORAGE_FAILED", "Persisted conversation messages are invalid.", false, { issues: parsed.error.issues }); return parsed.data; }
function clone<T>(value: T): T { if (Array.isArray(value)) return value.map((item) => clone(item)) as T; if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, child]) => [key, clone(child)])) as T; return value; }

export class SqliteConversationStore implements ConversationStore {
  constructor(private readonly database: DatabaseSync, private readonly budget: ConversationBudget = {}) {}
  async createSession(session: ConversationSession): Promise<void> { try { const now = new Date().toISOString(); transaction(this.database, () => { this.database.prepare("INSERT INTO sessions(id,state,created_at,updated_at) VALUES (?,?,?,?)").run(session.id, session.state, session.createdAt, now); session.turns.forEach((turn, index) => this.database.prepare("INSERT INTO conversation_turns(session_id,turn_index,messages_json) VALUES (?,?,?)").run(session.id, index, JSON.stringify(turn.messages))); }); } catch (error) { throw storageError(error); } }
  async getSession(id: string): Promise<ConversationSession | undefined> { try { const row = this.database.prepare("SELECT id,state,created_at FROM sessions WHERE id=?").get(id) as { id: string; state: "open" | "closed"; created_at: string } | undefined; if (!row) return undefined; const turns = this.readTurns(id); return freeze({ schemaVersion: 1, id: row.id, state: row.state, createdAt: row.created_at, history: turns.flatMap((turn) => turn.messages), turns }); } catch (error) { throw storageError(error); } }
  async closeSession(id: string): Promise<void> { try { this.database.prepare("UPDATE sessions SET state='closed',updated_at=? WHERE id=?").run(new Date().toISOString(), id); } catch (error) { throw storageError(error); } }
  async commitTurn(id: string, turn: ConversationTurn): Promise<void> { try { if (!turn.messages.length) throw failure("VALIDATION_FAILED", "Conversation turn cannot be empty."); transaction(this.database, () => { const session = this.database.prepare("SELECT state FROM sessions WHERE id=?").get(id) as { state: string } | undefined; if (!session || session.state !== "open") throw failure("STORAGE_FAILED", `Session '${id}' is unavailable.`); const row = this.database.prepare("SELECT COALESCE(MAX(turn_index), -1) AS turn_index FROM conversation_turns WHERE session_id=?").get(id) as { turn_index: number }; this.database.prepare("INSERT INTO conversation_turns(session_id,turn_index,messages_json) VALUES (?,?,?)").run(id, row.turn_index + 1, JSON.stringify(turn.messages)); this.database.prepare("UPDATE sessions SET updated_at=? WHERE id=?").run(new Date().toISOString(), id); }); } catch (error) { throw storageError(error); } }
  async snapshot(id: string): Promise<ConversationSnapshot> { const session = await this.getSession(id); if (!session || session.state !== "open") throw failure("STORAGE_FAILED", `Session '${id}' is unavailable.`); const turns = session.turns; const included = this.budget.maxTurns === undefined ? turns : turns.slice(Math.max(0, turns.length - this.budget.maxTurns)); return freeze({ history: included.flatMap((turn) => turn.messages), turns, turnsAvailable: turns.length, turnsIncluded: included.length, turnsDropped: turns.length - included.length }); }
  openSessionIds(): readonly string[] { try { return (this.database.prepare("SELECT id FROM sessions WHERE state='open' ORDER BY id").all() as Array<{ id: string }>).map((row) => row.id); } catch (error) { throw storageError(error); } }
  private readTurns(id: string): ConversationTurn[] { return (this.database.prepare("SELECT messages_json FROM conversation_turns WHERE session_id=? ORDER BY turn_index").all(id) as Array<{ messages_json: string }>).map((row) => ({ messages: validatedMessages(JSON.parse(row.messages_json)) })); }
}

export class SqliteScratchpadStore implements ScratchpadStore {
  constructor(private readonly database: DatabaseSync) {}
  async write(sessionId: string, key: string, content: string): Promise<ScratchpadMetadata> { try { const now = new Date().toISOString(); const existing = this.database.prepare("SELECT created_at FROM scratchpad_entries WHERE session_id=? AND key=?").get(sessionId, key) as { created_at: string } | undefined; this.database.prepare("INSERT INTO scratchpad_entries(session_id,key,content,bytes,created_at,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(session_id,key) DO UPDATE SET content=excluded.content,bytes=excluded.bytes,updated_at=excluded.updated_at").run(sessionId, key, content, Buffer.byteLength(content), existing?.created_at ?? now, now); return { key, bytes: Buffer.byteLength(content), createdAt: existing?.created_at ?? now, updatedAt: now }; } catch (error) { throw storageError(error); } }
  async append(sessionId: string, key: string, content: string): Promise<ScratchpadMetadata> { try { let metadata!: ScratchpadMetadata; transaction(this.database, () => { const existing = this.database.prepare("SELECT content,created_at FROM scratchpad_entries WHERE session_id=? AND key=?").get(sessionId, key) as { content: string; created_at: string } | undefined; if (!existing) throw new Error(`Scratchpad key '${key}' was not found.`); const value = `${existing.content}${content}`; const now = new Date().toISOString(); this.database.prepare("UPDATE scratchpad_entries SET content=?,bytes=?,updated_at=? WHERE session_id=? AND key=?").run(value, Buffer.byteLength(value), now, sessionId, key); metadata = { key, bytes: Buffer.byteLength(value), createdAt: existing.created_at, updatedAt: now }; }); return metadata; } catch (error) { throw storageError(error); } }
  async read(sessionId: string, key: string): Promise<ScratchpadEntry | undefined> { try { const row = this.database.prepare("SELECT session_id,key,content,bytes,created_at,updated_at FROM scratchpad_entries WHERE session_id=? AND key=?").get(sessionId, key) as { session_id: string; key: string; content: string; bytes: number; created_at: string; updated_at: string } | undefined; return row ? { sessionId: row.session_id, key: row.key, content: row.content, bytes: row.bytes, createdAt: row.created_at, updatedAt: row.updated_at } : undefined; } catch (error) { throw storageError(error); } }
  async list(sessionId: string): Promise<readonly ScratchpadMetadata[]> { try { return (this.database.prepare("SELECT key,bytes,created_at,updated_at FROM scratchpad_entries WHERE session_id=? ORDER BY key").all(sessionId) as Array<{ key: string; bytes: number; created_at: string; updated_at: string }>).map((row) => ({ key: row.key, bytes: row.bytes, createdAt: row.created_at, updatedAt: row.updated_at })); } catch (error) { throw storageError(error); } }
}

export class SqliteTaskStore implements TaskStore {
  constructor(private readonly database: DatabaseSync) {}
  async create(sessionId: string, objective: string, constraints: readonly string[] = []): Promise<Task> { try { const task = await new MemoryTaskStore().create(sessionId, objective, constraints); this.database.prepare("INSERT INTO tasks(session_id,task_id,version,payload_json,updated_at) VALUES (?,?,?,?,?)").run(sessionId, task.id, task.version, JSON.stringify(task), task.updatedAt); return clone(task); } catch (error) { throw storageError(error); } }
  async get(sessionId: string): Promise<Task | undefined> { try { const row = this.database.prepare("SELECT payload_json FROM tasks WHERE session_id=?").get(sessionId) as { payload_json: string } | undefined; return row ? parseTask(JSON.parse(row.payload_json)) : undefined; } catch (error) { throw storageError(error); } }
  async update(sessionId: string, taskId: string, expectedVersion: number, update: TaskUpdate): Promise<Task> { try { let result!: Task; transaction(this.database, () => { const row = this.database.prepare("SELECT payload_json,version,task_id FROM tasks WHERE session_id=?").get(sessionId) as { payload_json: string; version: number; task_id: string } | undefined; if (!row || row.task_id !== taskId) throw failure("CAPABILITY_UNAVAILABLE", "Task was not found for this session."); if (row.version !== expectedVersion) throw failure("CAPABILITY_CONFLICT", "Task update is stale.", false, { expectedVersion, actualVersion: row.version }); const current = parseTask(JSON.parse(row.payload_json)); result = applyTaskUpdate(current, update); this.database.prepare("UPDATE tasks SET version=?,payload_json=?,updated_at=? WHERE session_id=? AND version=?").run(result.version, JSON.stringify(result), result.updatedAt, sessionId, expectedVersion); }); return clone(result); } catch (error) { throw storageError(error); } }
}
function parseTask(value: unknown): Task { const parsed = taskSchema.safeParse(value); if (!parsed.success) throw failure("STORAGE_FAILED", "Persisted task state is invalid.", false, { issues: parsed.error.issues }); return clone(parsed.data); }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as Record<string, unknown>)) freeze(child); } return value; }
