import { MCPToolProvider } from "./adapters/tool-mcp.js";
import { realpathSync } from "node:fs";
import { resolve } from "node:path";
import { OllamaModelProvider } from "./adapters/model-ollama.js";
import { OpenAICompatibleModelProvider } from "./adapters/model-openai-compatible.js";
import { OpenAICodexModelProvider } from "./adapters/model-openai-codex.js";
import { ConversationContextOptions, InteractiveApprovalGateway } from "./application-gateway.js";
import { ConversationCompactor, ModelConversationCompactor } from "./compaction.js";
import { AllowAllToolAuthorizationPolicy, StaticToolAuthorizationPolicy } from "./authorization-mocks.js";
import { PortaConfig } from "./porta-config.js";
import { ConversationStore, ModelProvider, ToolContext, ToolProvider } from "./contracts.js";
import { MemoryConversationStore } from "./conversation.js";
import { ContentReducer as ReducerContract } from "./content-reducer.js";
import { FilesystemSearchSource, FilesystemToolProvider, ModelContentReducer } from "./filesystem.js";
import { MutationEngine } from "./mutation.js";
import { ExecutionToolProvider } from "./execution.js";
import { HostProcessRuntime } from "./adapters/runtime-host-process.js";
import { HostProcessSandbox } from "./adapters/sandbox-host-process.js";
import { BubblewrapSandbox } from "./adapters/sandbox-bubblewrap.js";
import { selectSandbox } from "./sandbox-selection.js";
import { CCCSearchEngine, GrepSearchEngine, LinearTextSearchEngine, RipgrepSearchEngine, SearchEngine, selectSearchEngine } from "./search.js";
import { MemoryScratchpadStore, ScratchpadSearchSource, ScratchpadStore, ScratchpadToolProvider } from "./scratchpad.js";
import { HarnessFailure, RuntimeHost, SandboxProvider, failure } from "./contracts.js";
import { planPlugins } from "./plugin-preflight.js";
import { PendingApprovalProvider } from "./approval-pending.js";
import { MemoryTaskStore, TaskStore, TaskToolProvider } from "./task.js";
import { CliGitBackend, GitBackend, GitToolProvider } from "./git.js";
import { openSqlitePersistence, SqlitePersistence } from "./persistence-sqlite.js";
import { ArtifactSearchSource, ArtifactStore, ArtifactToolProvider, MemoryArtifactStore } from "./artifact.js";
import { ToolRouter } from "./tools.js";
import { fetchAvailableModelOptions, ModelPicker } from "./model-picker.js";
import { ModelOption, ModelSelection } from "./contracts.js";
import { DelegatedTaskStore, DelegationOrchestrator, DelegationToolProvider } from "./delegation.js";
import { ProviderRegistry } from "./provider-registry.js";
import { DevelopmentReleaseCapabilities, DevelopmentRunner, DevelopmentPhaseDriver, GatewayDevelopmentPhaseDriver } from "./development-runner.js";
import { DockerImageAdapter, OneShotSshDeployment, qualifyDeployment } from "./deployment.js";
import { buildInfo } from "./build-info.js";

export interface ModelCatalogStatus { provider: string; status: "available" | "unavailable"; models: readonly ModelOption[]; error?: string }
export interface PortaApplication {
  readonly gateway: InteractiveApprovalGateway; readonly pendingApprovals: PendingApprovalProvider; readonly toolRouter: ToolRouter; readonly conversations: ConversationStore; readonly scratchpad: ScratchpadStore; readonly tasks: TaskStore; readonly artifacts: ArtifactStore; readonly searchEngines: { filesystem?: string; scratchpad: string }; readonly modelSelection: ModelSelection; readonly delegations: DelegatedTaskStore; readonly delegationOrchestrator: DelegationOrchestrator; readonly node: { version: string; name?: string; capabilities: readonly string[] }; readonly providers: ProviderRegistry; readonly developmentRunner: DevelopmentRunner;
  modelCatalog(): Promise<readonly ModelOption[]>; modelCatalogStatus(): Promise<ModelCatalogStatus>; start(): Promise<void>; shutdown(): Promise<void>;
}
export interface PortaFactories { skipModelHealth?: boolean; model?: (config: PortaConfig["model"]) => ModelProvider; taskStore?: TaskStore; artifactStore?: ArtifactStore; gitBackend?: GitBackend; mcp?: (config: import("./adapters/tool-mcp.js").McpStdioConfig) => MCPToolProvider; conversations?: ConversationStore; scratchpad?: ScratchpadStore; contentReducer?: ReducerContract; compactor?: ConversationCompactor; mutationEngine?: MutationEngine; executionRuntime?: RuntimeHost; executionSandbox?: SandboxProvider; executionSandboxes?: readonly SandboxProvider[]; developmentDriver?: DevelopmentPhaseDriver; developmentRelease?: DevelopmentReleaseCapabilities }

export async function createPortaApplication(config: PortaConfig, factories: PortaFactories = {}): Promise<PortaApplication> {
  const defaultProvider = (() => config.model.provider === "openai-codex" ? new OpenAICodexModelProvider(config.model) : config.model.provider === "openai-compatible" ? new OpenAICompatibleModelProvider(config.model) : new OllamaModelProvider(config.model))();
  const picker = new ModelPicker({ [config.model.provider]: defaultProvider }); const model = factories.model?.(config.model) ?? (await picker.selectProvider(config.model.provider));
  const modelFactory = factories.model ?? ((selection: PortaConfig["model"]) => selection.provider === "openai-codex" ? new OpenAICodexModelProvider(selection as Extract<PortaConfig["model"], { provider: "openai-codex" }>) : selection.provider === "openai-compatible" ? new OpenAICompatibleModelProvider(selection as Extract<PortaConfig["model"], { provider: "openai-compatible" }>) : new OllamaModelProvider(selection as Extract<PortaConfig["model"], { provider: "ollama" }>));
  const filesystemRoot = config.filesystem ? realpathSync(resolve(config.filesystem.root)) : undefined;
  const persistence: SqlitePersistence | undefined = config.persistence?.enabled ? await openSqlitePersistence(resolve(filesystemRoot ?? process.cwd(), config.persistence.path), config.conversation, config.persistence.maxArtifactBytes) : undefined;
  const mcpProviders = config.tools.map((tool) => factories.mcp?.({ providerId: tool.id, ...tool.transport }) ?? new MCPToolProvider({ providerId: tool.id, ...tool.transport }));
  const scratchpad = factories.scratchpad ?? persistence?.scratchpad ?? new MemoryScratchpadStore(); const tasks = factories.taskStore ?? persistence?.tasks ?? new MemoryTaskStore();
  for (const task of await tasks.list()) if (task.status === "active" && !task.development) await tasks.update(task.sessionId, task.id, task.version, { type: "set_status", status: "failed", reason: "execution_interrupted" });
  const providers = new ProviderRegistry(config); const artifacts = factories.artifactStore ?? persistence?.artifacts ?? new MemoryArtifactStore(config.persistence?.maxArtifactBytes);
  const delegationStore = new DelegatedTaskStore(scratchpad, { maxDepth: config.delegation?.maxDepth ?? 2, maxChildren: config.delegation?.maxChildren ?? 4 }, persistence?.delegations); if (persistence) await delegationStore.restore(await persistence.delegations.load());
  const parentPermissions = [...(config.delegation?.enabled ? ["agent.delegate"] : []), ...(config.filesystem ? ["filesystem.read", ...(config.filesystem.mutation?.enabled ? ["filesystem.write"] : [])] : []), ...(config.execution?.enabled ? ["execution"] : [])];
  const delegationProvider = config.delegation?.enabled ? new DelegationToolProvider(delegationStore, parentPermissions) : undefined; const delegationRegistration = delegationProvider ? [{ id: "agent", provider: delegationProvider as ToolProvider }] : [];
  const searchCandidates: readonly SearchEngine[] = [new CCCSearchEngine(), new RipgrepSearchEngine(), new GrepSearchEngine(), new LinearTextSearchEngine()]; const scratchpadEngine = selectSearchEngine(new ScratchpadSearchSource(scratchpad), searchCandidates) ?? new LinearTextSearchEngine(); const artifactEngine = selectSearchEngine(new ArtifactSearchSource(artifacts), searchCandidates) ?? new LinearTextSearchEngine();
  const conversations = factories.conversations ?? persistence?.conversations ?? new MemoryConversationStore(config.conversation); const filesystemEngine = filesystemRoot ? selectSearchEngine(new FilesystemSearchSource(filesystemRoot, config.filesystem?.maxReadBytes ?? 8 * 1024 * 1024), searchCandidates) ?? new LinearTextSearchEngine() : undefined;
  const filesystem = config.filesystem ? new FilesystemToolProvider(config.filesystem, factories.contentReducer ?? new ModelContentReducer(model), filesystemEngine, factories.mutationEngine) : undefined;
  let releaseGitBackend: GitBackend | undefined;
  const git = config.git?.enabled && filesystemRoot ? await (async () => { const backend = factories.gitBackend ?? new CliGitBackend({ root: filesystemRoot, executable: config.git!.executable, maxStatusEntries: config.git!.maxStatusEntries, maxDiffBytes: config.git!.maxDiffBytes, maxShowBytes: config.git!.maxShowBytes, maxLogEntries: config.git!.maxLogEntries }); const available = backend.available ? await backend.available() : true; if (available) releaseGitBackend = backend; return available ? new GitToolProvider(backend) : undefined; })() : undefined;
  const execution = config.execution?.enabled ? await (async () => { const executionConfig = config.execution!; if (!config.filesystem?.root || !filesystemRoot) throw new HarnessFailure({ code: "VALIDATION_FAILED", message: "Execution requires a configured filesystem root.", retryable: false }); const runtime = factories.executionRuntime ?? new HostProcessRuntime(); const host = new HostProcessSandbox(); const candidates = factories.executionSandboxes ?? [new BubblewrapSandbox({ workspaceRoot: filesystemRoot }), host]; const sandbox = factories.executionSandbox ?? (await selectSandbox({ filesystem: executionConfig.filesystem, network: executionConfig.network, codeLoading: executionConfig.codeLoading }, candidates.map((provider) => { const available = (provider as SandboxProvider & { available?: () => Promise<boolean> }).available; return available ? { provider, available: () => available.call(provider) } : { provider }; }), executionConfig.sandbox.preference)).provider; return new ExecutionToolProvider(runtime, sandbox, { workspaceRoot: filesystemRoot, allowedCommands: executionConfig.allowedCommands, defaultTimeoutMs: executionConfig.defaultTimeoutMs, maxStdoutBytes: executionConfig.maxStdoutBytes, maxStderrBytes: executionConfig.maxStderrBytes, maxArtifactBytes: config.persistence?.maxArtifactBytes, artifactStore: artifacts, policy: { filesystem: executionConfig.filesystem, network: executionConfig.network, codeLoading: executionConfig.codeLoading }, environment: executionConfig.environment, allowedEnvironmentKeys: executionConfig.allowedEnvironmentKeys }); })() : undefined;
  const registrations: readonly { id: string; provider: ToolProvider }[] = [...delegationRegistration, ...mcpProviders.map((provider) => ({ id: provider.providerId, provider })), ...(filesystem ? [{ id: "filesystem", provider: filesystem as ToolProvider }] : []), ...(execution ? [{ id: "execution", provider: execution as ToolProvider }] : []), ...(git ? [{ id: "git", provider: git as ToolProvider }] : []), { id: "artifact", provider: new ArtifactToolProvider(artifacts, artifactEngine, config.persistence?.maxArtifactContextBytes) }, { id: "scratchpad", provider: new ScratchpadToolProvider(scratchpad, scratchpadEngine) }, { id: "task", provider: new TaskToolProvider(tasks) }];
  const modelManifest = { schemaVersion: 1 as const, id: `model.${config.model.provider}`, version: "1", provides: [{ id: "model.text", version: "1" }, { id: "model.streaming", version: "1" }], requires: [] }; const manifests = [modelManifest, ...registrations.map((registration) => ({ schemaVersion: 1 as const, id: `tools.${registration.id}`, version: "1", provides: [{ id: "tools.discovery", version: "1" }, { id: "tools.invoke", version: "1" }], requires: [] }))]; const plan = planPlugins(manifests); if (plan.status !== "ready") { persistence?.close(); throw new HarnessFailure({ code: "PLUGIN_INVALID", message: "Porta plugin preflight failed.", retryable: false, details: plan.diagnostics }); }
  const healthy: { close?: () => Promise<void> }[] = [];
  try {
    if (!factories.skipModelHealth && "health" in model && typeof model.health === "function") { const status = await model.health(); if (status.status !== "healthy") throw new HarnessFailure({ code: "CAPABILITY_UNAVAILABLE", message: status.message ?? "Model provider is unhealthy.", retryable: false, details: status }); }
    for (const provider of mcpProviders) { const status = await provider.health(); if (status.status !== "healthy") throw new HarnessFailure({ code: "CAPABILITY_UNAVAILABLE", message: status.message ?? `Tool provider '${provider.providerId}' is unhealthy.`, retryable: false, details: status }); healthy.push(provider); }
    const router = new ToolRouter(); const context: ToolContext = { traceId: "startup", sessionId: "startup", executionId: "startup", signal: new AbortController().signal }; for (const registration of registrations) await router.register(registration.id, registration.provider, context);
    const pending = new PendingApprovalProvider(); const policy = config.authorization.mode === "allow-all" ? new AllowAllToolAuthorizationPolicy() : new StaticToolAuthorizationPolicy("require-approval"); delegationProvider?.setRunner(async (task) => { const selectedModel = task.requestedModel ?? config.model.model; const options = await fetchAvailableModelOptions(config.model.provider, "baseUrl" in config.model ? config.model.baseUrl : undefined); if (task.requestedModel && options.length && !options.some((option) => option.id === task.requestedModel)) throw new HarnessFailure({ code: "CAPABILITY_UNAVAILABLE", message: `Delegated model '${task.requestedModel}' is unavailable.`, retryable: false }); const childModel = selectedModel === config.model.model ? model : modelFactory({ ...config.model, model: selectedModel } as PortaConfig["model"]); return new DelegationOrchestrator(delegationStore).runAttempt({ taskId: task.id, model: childModel, tools: router, policy, approvalProvider: pending, budget: task.budget }); });
    const compaction = config.conversation.compaction; const contextOptions: ConversationContextOptions = { ...(compaction ? { enabled: compaction.enabled, threshold: config.conversation.maxTurns, keepRecentTurns: compaction.keepRecentTurns, maxManifestEntries: compaction.maxManifestEntries, compactor: factories.compactor ?? new ModelConversationCompactor(model) } : {}), scratchpad, taskStore: tasks };
    const gateway = new InteractiveApprovalGateway(model, router, pending, policy, { maxSteps: config.agent.maxSteps ?? 8, maxToolCalls: config.agent.maxToolCalls ?? 16 }, conversations, contextOptions, (selection) => { const configured = providers.byType(selection.provider); const base = configured ? { provider: selection.provider, baseUrl: configured.endpoint, model: selection.model } : { ...config.model, provider: selection.provider, model: selection.model }; return modelFactory(base as PortaConfig["model"]); });
    const configuredRelease = factories.developmentRelease ?? createConfiguredRelease(config, releaseGitBackend, filesystemRoot); const developmentRunner = new DevelopmentRunner(tasks, factories.developmentDriver ?? new GatewayDevelopmentPhaseDriver(gateway), { release: configuredRelease, localQualification: { async qualify(input) { const info = buildInfo(); const task = await tasks.get(input.sessionId); const correctRevision = Boolean(input.expectedRevision) && (info.commit === input.expectedRevision || input.expectedRevision.startsWith(info.commit) || info.commit.startsWith(input.expectedRevision)); return { ready: true, correctRevision, taskStateAvailable: task?.id === input.taskId, observedRevision: info.commit, ...(correctRevision && task?.id === input.taskId ? {} : { message: "Local replacement qualification did not match the expected task or revision." }) }; } } }); let stopped = false;
    return { gateway, pendingApprovals: pending, toolRouter: router, conversations, scratchpad, tasks, artifacts, delegations: delegationStore, developmentRunner, delegationOrchestrator: new DelegationOrchestrator(delegationStore), node: { version: "0.1.0", capabilities: ["models.catalog", "sessions.create", "sessions.resume", "execution.stream", "tasks.list", "tasks.delete", ...(config.persistence?.enabled ? ["persistence"] : []), ...(filesystem ? ["filesystem.read"] : []), ...(execution ? ["command.execute"] : []), ...(config.delegation?.enabled ? ["delegation.create"] : []), ...(config.authorization.mode ? ["approvals"] : []), "providers.list", "providers.configure", "providers.test", "providers.delete"] }, providers, searchEngines: { ...(filesystemEngine ? { filesystem: filesystemEngine.name } : {}), scratchpad: scratchpadEngine.name }, modelSelection: { provider: config.model.provider, model: config.model.model }, async modelCatalog() { const discovered = await providers.models(); const options = discovered.length ? discovered : await fetchAvailableModelOptions(config.model.provider, "baseUrl" in config.model ? config.model.baseUrl : undefined); return options.length ? options : [{ id: config.model.model, displayName: config.model.model, provider: config.model.provider }]; }, async modelCatalogStatus() { try { const discovered = await providers.models(); const options = discovered.length ? discovered : await fetchAvailableModelOptions(config.model.provider, "baseUrl" in config.model ? config.model.baseUrl : undefined); return { provider: config.model.provider, status: options.length ? "available" as const : "unavailable" as const, models: options.length ? options : [{ id: config.model.model, displayName: config.model.model, provider: config.model.provider }], ...(options.length ? {} : { error: "Provider discovery returned no models." }) }; } catch (error) { return { provider: config.model.provider, status: "unavailable" as const, models: [{ id: config.model.model, displayName: config.model.model, provider: config.model.provider }], error: error instanceof Error ? error.message.replace(/(token|authorization|password|secret)[^\n]*/gi, "$1 unavailable") : "Provider discovery failed." }; } }, async start() { if (stopped) throw new Error("Porta application is shut down."); for (const task of await tasks.list()) if (task.development && ["deploying", "health_checking"].includes(task.development.phase) && ["prepared", "triggered", "awaiting_recovery"].includes(task.development.deployment?.status ?? "")) await developmentRunner.recover(task.sessionId); }, async shutdown() { if (stopped) return; stopped = true; await gateway.shutdown(); for (const provider of [...mcpProviders].reverse()) await provider.close(); persistence?.close(); } };
  } catch (error) { for (const provider of [...healthy].reverse()) await provider.close?.(); persistence?.close(); throw error; }
}
function createConfiguredRelease(config: PortaConfig, git: GitBackend | undefined, workspaceRoot: string | undefined): DevelopmentReleaseCapabilities | undefined { const deployment = config.deployment; if (!deployment || !git?.commit || !git.push || !workspaceRoot || !process.env.PORTA_DEPLOYMENT_HEALTH_ENDPOINT) return undefined; const image = new DockerImageAdapter({ workspaceRoot, imageRepository: deployment.imageRepository, registry: deployment.registry }); const ssh = new OneShotSshDeployment({ target: "deploy_porta@nas" }); const healthEndpoint = process.env.PORTA_DEPLOYMENT_HEALTH_ENDPOINT; const healthHeaders = process.env.PORTA_DEPLOYMENT_HEALTH_TOKEN ? { Authorization: `Bearer ${process.env.PORTA_DEPLOYMENT_HEALTH_TOKEN}` } : undefined; return { async commit(input) { return git.commit!(input, { signal: new AbortController().signal }); }, async push(input) { const result = await git.push!({ signal: new AbortController().signal }); if (result.revision !== input.revision || !result.revision) throw failure("CAPABILITY_CONFLICT", "Pushed revision does not match the committed revision."); return { ...result, revision: result.revision }; }, async build(input) { return image.build(input.revision, input.tag); }, async pushImage(input) { return image.push(input); }, async deploy(input) { const result = await ssh.deploy({ sourceRevision: input.sourceRevision, imageReference: input.imageReference, ...(input.previousRevision ? { previousRevision: input.previousRevision } : {}), ...(input.previousImageReference ? { previousImageReference: input.previousImageReference } : {}) }); return { status: result.status, ...(result.stdout ? { stdout: result.stdout } : {}), ...(result.stderr ? { stderr: result.stderr } : {}), ...(result.exitCode !== undefined ? { exitCode: result.exitCode } : {}) }; }, async qualify(input) { return qualifyDeployment(healthEndpoint, input.expectedRevision, fetch, { taskId: input.taskId, ...(healthHeaders ? { headers: healthHeaders } : {}) }); } }; }
/** @deprecated Use PortaApplication. */
export type HarnessApplication = PortaApplication;
/** @deprecated Use PortaFactories. */
export type HarnessFactories = PortaFactories;
/** @deprecated Use createPortaApplication. */
export const createHarnessApplication = createPortaApplication;
