import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { generateRegistrationOptions, generateAuthenticationOptions, verifyRegistrationResponse, verifyAuthenticationResponse } from "@simplewebauthn/server";
export interface WebAuthnConfig { rpID: string; rpName: string; origin: string }
export interface WebAuthnCredential { credentialId: string; publicKey: string; counter: number; createdAt: string; lastUsedAt?: string; displayName: string; transports?: string[] }
interface Pending { challenge: string; type: "register" | "login"; expiresAt: number }
export class WebAuthnService {
 private credentials: WebAuthnCredential[]; private readonly pending = new Map<string, Pending>(); private readonly userId: string; private readonly now: () => number;
 constructor(private readonly directory: string, readonly config: WebAuthnConfig, now: () => number = Date.now) { this.now = now; const file = join(directory, "webauthn.json"); const data = existsSync(file) ? JSON.parse(readFileSync(file, "utf8")) as { userId: string; credentials: WebAuthnCredential[] } : { userId: randomBytes(16).toString("base64url"), credentials: [] }; this.userId = data.userId; this.credentials = data.credentials; if (!existsSync(file)) this.persist(); }
 list(): readonly WebAuthnCredential[] { return this.credentials.map((credential) => ({ ...credential })); }
 hasCredentials(): boolean { return this.credentials.length > 0; }
 async registrationOptions(): Promise<unknown> { this.cleanup(); const transaction = randomBytes(16).toString("base64url"); const options = await generateRegistrationOptions({ rpName: this.config.rpName, rpID: this.config.rpID, userName: "Porta Administrator", userDisplayName: "Porta Administrator", userID: Buffer.from(this.userId), attestationType: "none", excludeCredentials: this.credentials.map((c) => ({ id: c.credentialId, transports: c.transports as any })), authenticatorSelection: { residentKey: "preferred", userVerification: "preferred" } }); this.pending.set(transaction, { challenge: options.challenge, type: "register", expiresAt: this.now() + 300_000 }); return { transaction, options }; }
 async register(transaction: string, response: any, displayName = "Passkey"): Promise<void> { const pending = this.consume(transaction, "register"); const verification = await verifyRegistrationResponse({ response, expectedChallenge: pending.challenge, expectedOrigin: this.config.origin, expectedRPID: this.config.rpID }); if (!verification.verified || !verification.registrationInfo) throw new Error("WEBAUTHN_REGISTRATION_INVALID"); const info: any = verification.registrationInfo; const credential = info.credential ?? info; this.credentials.push({ credentialId: typeof credential.id === "string" ? credential.id : Buffer.from(credential.id).toString("base64url"), publicKey: Buffer.from(credential.publicKey).toString("base64url"), counter: credential.counter ?? 0, createdAt: new Date(this.now()).toISOString(), displayName, transports: response.response?.transports }); this.persist(); }
 async loginOptions(): Promise<unknown> { this.cleanup(); if (!this.hasCredentials()) throw new Error("WEBAUTHN_NOT_ENROLLED"); const transaction = randomBytes(16).toString("base64url"); const options = await generateAuthenticationOptions({ rpID: this.config.rpID, userVerification: "preferred", allowCredentials: this.credentials.map((c) => ({ id: c.credentialId, transports: c.transports as any })) }); this.pending.set(transaction, { challenge: options.challenge, type: "login", expiresAt: this.now() + 300_000 }); return { transaction, options }; }
 async login(transaction: string, response: any): Promise<WebAuthnCredential> { const pending = this.consume(transaction, "login"); const id = typeof response.id === "string" ? response.id : Buffer.from(response.rawId, "base64url").toString("base64url"); const credential = this.credentials.find((c) => c.credentialId === id); if (!credential) throw new Error("WEBAUTHN_CREDENTIAL_UNKNOWN"); const verification = await verifyAuthenticationResponse({ response, expectedChallenge: pending.challenge, expectedOrigin: this.config.origin, expectedRPID: this.config.rpID, credential: { id: credential.credentialId, publicKey: Buffer.from(credential.publicKey, "base64url"), counter: credential.counter, transports: credential.transports as any } }); if (!verification.verified) throw new Error("WEBAUTHN_ASSERTION_INVALID"); credential.counter = verification.authenticationInfo.newCounter; credential.lastUsedAt = new Date(this.now()).toISOString(); this.persist(); return { ...credential }; }
 remove(id: string): void { if (this.credentials.length <= 1) throw new Error("WEBAUTHN_FINAL_CREDENTIAL"); this.credentials = this.credentials.filter((c) => c.credentialId !== id); this.persist(); }
 private consume(transaction: string, type: Pending["type"]): Pending { this.cleanup(); const pending = this.pending.get(transaction); if (!pending || pending.type !== type) throw new Error("WEBAUTHN_CHALLENGE_UNKNOWN"); this.pending.delete(transaction); if (pending.expiresAt <= this.now()) throw new Error("WEBAUTHN_CHALLENGE_EXPIRED"); return pending; }
 private cleanup(): void { const now = this.now(); for (const [id, pending] of this.pending) if (pending.expiresAt <= now) this.pending.delete(id); }
 private persist(): void { writeFileSync(join(this.directory, "webauthn.json"), JSON.stringify({ userId: this.userId, credentials: this.credentials }, null, 2) + "\n", { mode: 0o600 }); }
}
