import { credentialToJSON, loginOptionsForBrowser, registrationOptionsForBrowser } from "./webauthn.js";

const $ = (selector) => document.querySelector(selector);
const app = $("#app");
const authGate = $("#auth-gate");
const authMessage = $("#auth-message");
const tabsElement = $("#session-tabs");
const attentionButton = $("#attention-button");
const attentionPopover = $("#attention-popover");
const emptyState = $("#empty-state");
const workspace = $("#workspace");
const sessionTitle = $("#session-title");
const sessionSubtitle = $("#session-subtitle");
const sessionTarget = $("#session-target");
const sessionModel = $("#session-model");
const sessionStatus = $("#session-status");
const sessionAttention = $("#session-attention");
const activity = $("#activity");
const activitySummary = $("#activity-summary");
const composer = $("#composer");
const composerInput = $("#composer-input");
const send = $("#send");
const composerStatus = $("#composer-status");
const taskActions = $("#task-actions");
const newSessionDialog = $("#new-session-dialog");
const newSessionForm = $("#new-session-form");
const newTarget = $("#new-target");
const newModel = $("#new-model");
const newSession = $("#new-session");
const emptyNewSession = $("#empty-new-session");
const openSettings = $("#open-settings");
const settingsDialog = $("#settings-dialog");
const closeSettings = $("#close-settings");
const renameSession = $("#rename-session");
const stopSession = $("#stop-session");
const deleteSession = $("#delete-session");
const providerList = $("#provider-list");
const addProvider = $("#add-provider");
const targetList = $("#target-list");
const identityList = $("#identity-list");
const identityForm = $("#identity-form");
const pairingPayload = $("#pairing-payload");
const pairTarget = $("#pair-target");
const pairingStatus = $("#pairing-status");
const systemInfo = $("#system-info");
const passkeyAuth = $("#passkey-auth");

const UI_VERSION = "porta-ui-v3";
const state = { sessions: new Map(), activeSessionId: undefined, targets: [], models: [], running: false, attentionOpen: false };

function targetUrl(path, targetId) { const target = targetId ?? activeSession()?.targetId ?? "local"; return `${path}${path.includes("?") ? "&" : "?"}target=${encodeURIComponent(target)}`; }
function activeSession() { return state.sessions.get(state.activeSessionId); }
function persist() { localStorage.setItem("porta-ui-state", JSON.stringify({ version: UI_VERSION, activeSessionId: state.activeSessionId, sessions: [...state.sessions.values()].map(({ id, targetId, model, title, draft }) => ({ id, targetId, model, title, draft })) })); }
function attentionLabel(attention) { return ({ approval_required: "Approval required", provide_input: "Input required", target_unavailable: "Target unavailable", execution_failed: "Execution failed" }[attention?.reason] ?? (attention?.reason ? attention.reason.replaceAll("_", " ") : "Needs attention")); }
function statusLabel(status) { return ({ active: "Running", working: "Running", waiting: "Waiting", completed: "Completed", failed: "Failed", cancelled: "Cancelled", blocked: "Blocked" }[status] ?? "Ready"); }
function statusClass(status) { return ({ active: "working", working: "working", waiting: "waiting", completed: "completed", failed: "failed", cancelled: "cancelled" }[status] ?? ""); }

async function jsonFetch(url, options = {}) { const response = await fetch(url, options); let body = {}; try { body = await response.json(); } catch {} if (!response.ok) throw new Error(body.error?.message ?? body.error ?? `Request failed (${response.status})`); return body; }
async function authenticateUi() { let response = await fetch("/auth/webauthn/register/options", { method: "POST" }); let body = await response.json(); const registration = response.ok; if (!registration) { response = await fetch("/auth/webauthn/login/options", { method: "POST" }); body = await response.json(); } if (!response.ok) throw new Error(body.error || "Passkey authentication unavailable."); const options = registration ? registrationOptionsForBrowser(body.options) : loginOptionsForBrowser(body.options); const credential = registration ? await navigator.credentials.create({ publicKey: options }) : await navigator.credentials.get({ publicKey: options }); const endpoint = registration ? "/auth/webauthn/register/verify" : "/auth/webauthn/login/verify"; await jsonFetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transaction: body.transaction, response: credentialToJSON(credential) }) }); }
async function ensureAuth() { const response = await fetch("/auth/status"); const status = await response.json(); if (status.authenticated) return true; authGate.hidden = false; passkeyAuth.onclick = async () => { passkeyAuth.disabled = true; try { await authenticateUi(); location.reload(); } catch (error) { authMessage.textContent = error instanceof Error ? error.message : "Authentication failed."; passkeyAuth.disabled = false; } }; return false; }

function loadPersisted() { try { const saved = JSON.parse(localStorage.getItem("porta-ui-state") || "null"); if (saved?.version !== UI_VERSION) return; state.activeSessionId = saved.activeSessionId; for (const session of saved.sessions ?? []) if (session?.id) state.sessions.set(session.id, { ...session, status: "ready", activity: [], attention: undefined }); } catch {} }
function renderTabs() { tabsElement.replaceChildren(); for (const session of state.sessions.values()) { const button = document.createElement("button"); button.type = "button"; button.className = `session-tab${session.id === state.activeSessionId ? " active" : ""}`; button.title = session.title; const title = document.createElement("span"); title.className = "session-tab-title"; title.textContent = session.title || "New session"; const meta = document.createElement("small"); meta.className = "session-tab-meta"; meta.textContent = `${session.targetId}${session.attention?.required ? " · !" : session.status === "completed" ? " · ✓" : ""}`; button.append(title, meta); button.onclick = () => activateSession(session.id); tabsElement.append(button); } const add = document.createElement("button"); add.type = "button"; add.className = "session-tab new-tab"; add.textContent = "+"; add.title = "New session"; add.onclick = () => newSessionDialog.showModal(); tabsElement.append(add); }
function renderAttention() { const affected = [...state.sessions.values()].filter((session) => session.attention?.required); attentionButton.hidden = affected.length === 0; attentionButton.textContent = affected.length ? `⚠ ${affected.length}` : ""; attentionButton.title = affected.length ? "Sessions needing attention" : ""; if (!affected.length) { attentionPopover.hidden = true; return; } attentionPopover.replaceChildren(); for (const session of affected) { const button = document.createElement("button"); button.type = "button"; button.className = "attention-item"; button.textContent = `${session.title} · ${attentionLabel(session.attention)}`; button.onclick = () => { attentionPopover.hidden = true; activateSession(session.id); requestAnimationFrame(() => (activity.querySelector(".approval") ?? activity).scrollIntoView({ behavior: "smooth", block: "start" })); }; attentionPopover.append(button); } }
function renderActivity(session) { activity.replaceChildren(); if (!session.activity.length) { const empty = document.createElement("div"); empty.className = "activity-empty"; empty.innerHTML = "<div><strong>No activity yet</strong><p>Describe what Porta should work on below.</p></div>"; activity.append(empty); return; } for (const item of session.activity) { if (item.kind === "approval") { const box = document.createElement("article"); box.className = "approval"; box.dataset.approvalId = item.approvalId; const heading = document.createElement("h3"); heading.textContent = `Approval required · ${item.toolId}`; const detail = document.createElement("pre"); detail.textContent = JSON.stringify(item.input, null, 2); const actions = document.createElement("div"); actions.className = "approval-actions"; for (const [decision, label] of [["approve", "Approve"], ["deny", "Reject"]]) { const button = document.createElement("button"); button.type = "button"; button.textContent = label; button.className = decision === "approve" ? "approve" : ""; button.onclick = () => resolveApproval(item, decision); actions.append(button); } box.append(heading, detail, actions); activity.append(box); continue; } const entry = document.createElement("article"); entry.className = `activity-entry ${item.kind ?? "note"}`; const label = document.createElement("div"); label.className = "activity-label"; label.textContent = item.label; const content = document.createElement("div"); content.className = item.kind === "note" ? "activity-note" : "activity-content"; content.textContent = item.text; entry.append(label, content); activity.append(entry); } }
function renderSession() { const session = activeSession(); if (!session) { workspace.hidden = true; emptyState.hidden = false; return; } workspace.hidden = false; emptyState.hidden = true; sessionTitle.textContent = session.title || "New session"; sessionSubtitle.textContent = session.lastActivity || "Ready to begin"; sessionStatus.textContent = session.currentStatus || statusLabel(session.status); sessionStatus.className = `status-chip ${statusClass(session.status)}`; sessionAttention.hidden = !session.attention?.required; sessionAttention.textContent = session.attention?.required ? attentionLabel(session.attention) : ""; fillSelect(sessionTarget, state.targets.map((target) => ({ value: target.id, label: target.id })), session.targetId); fillSelect(sessionModel, state.models.map((model) => ({ value: `${model.provider}/${model.id}`, label: model.displayName || model.id })), session.model); renderActivity(session); renderTaskActions(session); send.disabled = state.running; stopSession.disabled = !session.sessionId || (!state.running && !["waiting", "working"].includes(session.status)); deleteSession.disabled = !session.sessionId; composerStatus.textContent = state.running ? "Porta is working…" : "Enter to send · Shift+Enter for a new line"; }
function fillSelect(select, options, selected) { select.replaceChildren(); if (!options.length) { const option = document.createElement("option"); option.textContent = "Unavailable"; select.append(option); select.disabled = true; return; } select.disabled = false; for (const item of options) { const option = document.createElement("option"); option.value = item.value; option.textContent = item.label; option.selected = item.value === selected; select.append(option); } }
function addActivity(session, item) { session.activity.push(item); if (session.activity.length > 100) session.activity.shift(); session.lastActivity = item.text || item.label; renderSession(); }
function renderTaskActions(session) { taskActions.replaceChildren(); const task = session.task; if (!task?.development) { taskActions.hidden = true; return; } taskActions.hidden = false; if (task.pendingIntervention) { const action = task.pendingIntervention.action === "approve" ? ["Approve", "approve"] : task.pendingIntervention.action === "provide_input" ? ["Provide input", "provide_input"] : ["Resume", "resume"]; const button = document.createElement("button"); button.className = "primary"; button.type = "button"; button.textContent = action[0]; button.onclick = () => intervene(task, action[1]); taskActions.append(button); if (action[1] === "approve") { const reject = document.createElement("button"); reject.className = "secondary"; reject.type = "button"; reject.textContent = "Reject"; reject.onclick = () => intervene(task, "reject"); taskActions.append(reject); } } else if (task.phase === "ready_for_commit") { const button = document.createElement("button"); button.className = "primary"; button.type = "button"; button.textContent = "Release"; button.onclick = () => runTaskAction(task, "release"); taskActions.append(button); } else if (task.phase && !["completed", "failed", "blocked"].includes(task.phase)) { const button = document.createElement("button"); button.className = "primary"; button.type = "button"; button.textContent = "Run"; button.onclick = () => runTaskAction(task, "run"); taskActions.append(button); } }
async function runTaskAction(task, action) { try { await jsonFetch(targetUrl(`/api/tasks/${encodeURIComponent(task.id)}/${action}`)); await refreshSession(activeSession()); } catch (error) { addActivity(activeSession(), { kind: "note error", label: "Error", text: error instanceof Error ? error.message : "Task action failed." }); } }
async function intervene(task, action) { let input; if (action === "provide_input") input = window.prompt("Input for this session:") ?? undefined; try { await jsonFetch(targetUrl(`/api/tasks/${encodeURIComponent(task.id)}/intervention`), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ version: task.version, action, ...(input ? { input } : {}) }) }); await refreshSession(activeSession()); } catch (error) { addActivity(activeSession(), { kind: "note error", label: "Error", text: error instanceof Error ? error.message : "Intervention failed." }); } }
async function resolveApproval(item, decision) { try { await jsonFetch(targetUrl(`/api/approvals/${encodeURIComponent(item.approvalId)}`), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }); const session = activeSession(); session.activity = session.activity.filter((entry) => entry.approvalId !== item.approvalId); session.attention = undefined; renderSession(); renderTabs(); renderAttention(); } catch (error) { addActivity(activeSession(), { kind: "note error", label: "Error", text: error instanceof Error ? error.message : "Approval failed." }); } }
async function refreshSession(session) { if (!session?.sessionId) return; try { const task = await jsonFetch(targetUrl(`/api/sessions/${encodeURIComponent(session.sessionId)}/task`, session.targetId)); session.task = task; session.status = task.status; session.attention = task.attention?.required ? task.attention : session.attention; renderTabs(); renderAttention(); if (session.id === state.activeSessionId) renderSession(); } catch {} }
async function activateSession(id) { if (!state.sessions.has(id)) return; state.activeSessionId = id; const session = activeSession(); session.attention &&= session.attention; persist(); renderTabs(); renderAttention(); renderSession(); if (session.sessionId) { await hydrateSession(session); await loadApprovals(session); await refreshSession(session); } }
async function hydrateSession(session) { try { const result = await jsonFetch(targetUrl(`/api/sessions/${encodeURIComponent(session.sessionId)}`, session.targetId)); session.activity = []; for (const message of result.history ?? []) if (message?.role) session.activity.push({ kind: message.role === "user" ? "user" : "assistant", label: message.role === "user" ? "You" : "Porta", text: typeof message.content === "string" ? message.content : JSON.stringify(message.content) }); renderSession(); } catch {} }
async function loadApprovals(session) { try { const result = await jsonFetch(targetUrl("/api/approvals/pending", session.targetId)); for (const approval of result.approvals ?? []) if (approval.sessionId === session.sessionId && !session.activity.some((item) => item.approvalId === approval.approvalId)) { session.activity.push({ kind: "approval", label: "Approval", approvalId: approval.approvalId, toolId: approval.toolId, input: approval.input }); session.attention = { required: true, reason: "approval_required" }; } renderSession(); renderTabs(); renderAttention(); } catch {} }
async function loadTargets() { try { const result = await jsonFetch("/api/execution-targets"); state.targets = [{ id: "local" }, ...(result.targets ?? [])]; } catch { state.targets = [{ id: "local" }]; } }
async function loadModels() { try { const result = await jsonFetch(targetUrl("/api/models", "local")); state.models = result.models ?? []; } catch { state.models = []; } }
async function loadSessions() { const targets = [...new Set(state.targets.map((target) => target.id))]; const discovered = []; for (const targetId of targets) { try { const result = await jsonFetch(targetUrl("/api/sessions", targetId)); discovered.push(...(result.sessions ?? []).map((session) => ({ ...session, targetId }))); } catch {} } for (const summary of discovered) { const id = `session-${summary.sessionId}`; const existing = state.sessions.get(id); state.sessions.set(id, { ...(existing ?? {}), id, sessionId: summary.sessionId, targetId: summary.target || summary.targetId, taskId: summary.task?.id, title: summary.task?.objective || existing?.title || "Recovered session", status: summary.task?.status || existing?.status || "ready", task: existing?.task }); } if (!state.activeSessionId || !state.sessions.has(state.activeSessionId)) state.activeSessionId = [...state.sessions.keys()][0]; persist(); renderTabs(); renderAttention(); }
async function submit(text) { const session = activeSession(); if (!session || state.running || !session.sessionId) return; state.running = true; session.status = "working"; session.currentStatus = "Running"; if (session.title === "New session") session.title = text.slice(0, 48); session.activity.push({ kind: "user", label: "You", text }); renderSession(); renderTabs(); const assistant = { kind: "assistant", label: "Porta", text: "" }; session.activity.push(assistant); renderSession(); try { const response = await fetch(targetUrl(`/api/sessions/${encodeURIComponent(session.sessionId)}/messages`, session.targetId), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ input: text }) }); if (!response.ok || !response.body) throw new Error("Porta could not start this session."); const reader = response.body.pipeThrough(new TextDecoderStream()).getReader(); let buffer = ""; while (true) { const next = await reader.read(); if (next.done) break; buffer += next.value; const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) if (line) handleEvent(session, JSON.parse(line), assistant); } if (buffer) handleEvent(session, JSON.parse(buffer), assistant); } catch (error) { addActivity(session, { kind: "note error", label: "Error", text: error instanceof Error ? error.message : "Request failed." }); session.status = "failed"; session.attention = { required: true, reason: "execution_failed" }; } finally { state.running = false; session.currentStatus = statusLabel(session.status); persist(); renderSession(); renderTabs(); renderAttention(); await refreshSession(session); } }
function handleEvent(session, event, assistant) { if (event.type === "OutputDelta") { assistant.text += event.text; renderSession(); } else if (event.type === "ToolStarted") addActivity(session, { kind: "note tool", label: "Working", text: event.toolId }); else if (event.type === "ToolCompleted") addActivity(session, { kind: event.result?.error ? "note error" : "note", label: event.result?.error ? "Failed" : "Completed", text: event.result?.error?.message ?? event.toolId }); else if (event.type === "ApprovalRequested") { session.activity.push({ kind: "approval", label: "Approval", approvalId: event.approvalId, toolId: event.toolId, input: event.input }); session.attention = { required: true, reason: "approval_required" }; session.status = "waiting"; renderSession(); renderTabs(); renderAttention(); } else if (event.type === "ExecutionCompleted") { session.status = "completed"; session.attention = undefined; } else if (event.type === "ExecutionCancelled") session.status = "cancelled"; else if (event.type === "Error") { session.status = "failed"; session.attention = { required: true, reason: "execution_failed" }; addActivity(session, { kind: "note error", label: "Failed", text: event.error?.message ?? "Execution failed." }); } }
async function createSession(targetId, model) { const body = model ? { model: { provider: model.split("/")[0], model: model.split("/").slice(1).join("/") } } : {}; const result = await jsonFetch(targetUrl("/api/sessions", targetId), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); return result.sessionId; }
async function openNewSession(targetId, model) { const id = `session-${crypto.randomUUID()}`; const sessionId = await createSession(targetId, model); const session = { id, sessionId, targetId, model, title: "New session", status: "ready", activity: [], attention: undefined }; state.sessions.set(id, session); state.activeSessionId = id; persist(); renderTabs(); renderSession(); newSessionDialog.close(); }
function populateNewSession() { fillSelect(newTarget, state.targets.map((target) => ({ value: target.id, label: target.id })), "local"); fillSelect(newModel, [{ value: "", label: "Default model" }, ...state.models.map((model) => ({ value: `${model.provider}/${model.id}`, label: model.displayName || model.id }))], ""); }
async function renderSettings() { try { const providers = await jsonFetch("/api/providers"); providerList.replaceChildren(...(providers.providers ?? []).map((provider) => { const row = document.createElement("div"); row.className = "settings-row"; row.textContent = `${provider.name} · ${provider.status} · ${provider.modelCount} models`; return row; })); } catch { providerList.textContent = "Provider information unavailable."; } targetList.replaceChildren(...state.targets.map((target) => { const row = document.createElement("div"); row.className = "settings-row"; row.textContent = target.id; return row; })); try { const identities = await jsonFetch("/api/identity/allowed"); identityList.replaceChildren(...(identities.identities ?? []).map((identity) => { const row = document.createElement("div"); row.className = "settings-row"; row.textContent = `${identity.displayName} · ${identity.enabled ? "Enabled" : "Disabled"}`; return row; })); } catch { identityList.textContent = "Identity information unavailable."; } try { const node = await jsonFetch("/api/node"); systemInfo.textContent = JSON.stringify(node, null, 2); } catch { systemInfo.textContent = "System information unavailable."; } }

newSession.onclick = () => { populateNewSession(); newSessionDialog.showModal(); };
emptyNewSession.onclick = newSession.onclick;
newSessionForm.addEventListener("submit", async (event) => { event.preventDefault(); const button = $("#create-session"); button.disabled = true; try { await openNewSession(newTarget.value || "local", newModel.value || undefined); } catch (error) { authMessage.textContent = error instanceof Error ? error.message : "Session creation failed."; } finally { button.disabled = false; } });
attentionButton.onclick = () => { const affected = [...state.sessions.values()].filter((session) => session.attention?.required); if (affected.length === 1) { activateSession(affected[0].id); requestAnimationFrame(() => activity.scrollIntoView({ behavior: "smooth" })); } else attentionPopover.hidden = !attentionPopover.hidden; };
openSettings.onclick = async () => { await renderSettings(); settingsDialog.showModal(); };
addProvider.onclick = async () => { const type = prompt("Provider type (openai-compatible or ollama)", "openai-compatible"); if (type !== "openai-compatible" && type !== "ollama") return; const name = prompt("Provider name", type === "ollama" ? "Ollama" : "OpenAI-compatible server"); const endpoint = name && prompt("Base URL", type === "ollama" ? "http://127.0.0.1:11434" : "http://127.0.0.1:8080/v1"); if (!name || !endpoint) return; try { await jsonFetch("/api/providers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), name, type, endpoint }) }); await renderSettings(); await loadModels(); } catch (error) { systemInfo.textContent = error instanceof Error ? error.message : "Provider update failed."; } };
closeSettings.onclick = () => settingsDialog.close();
settingsDialog.addEventListener("click", (event) => { if (event.target === settingsDialog) settingsDialog.close(); });
renameSession.onclick = () => { const session = activeSession(); const title = window.prompt("Session name", session?.title || "New session"); if (title?.trim() && session) { session.title = title.trim(); persist(); renderTabs(); renderSession(); } };
stopSession.onclick = async () => { const session = activeSession(); if (!session?.sessionId || !confirm("Stop this session? Its history will be retained.")) return; try { await jsonFetch(targetUrl(`/api/sessions/${encodeURIComponent(session.sessionId)}/cancel`, session.targetId), { method: "POST" }); session.status = "cancelled"; state.running = false; renderSession(); renderTabs(); } catch (error) { addActivity(session, { kind: "note error", label: "Error", text: error instanceof Error ? error.message : "Stop failed." }); } };
deleteSession.onclick = async () => { const session = activeSession(); if (!session?.sessionId || state.running || !confirm("Delete this session?")) return; try { await jsonFetch(targetUrl(`/api/sessions/${encodeURIComponent(session.sessionId)}`, session.targetId), { method: "DELETE" }); state.sessions.delete(session.id); state.activeSessionId = [...state.sessions.keys()][0]; persist(); renderTabs(); renderSession(); } catch (error) { addActivity(session, { kind: "note error", label: "Error", text: error instanceof Error ? error.message : "Delete failed." }); } };
sessionTarget.addEventListener("change", async () => { const session = activeSession(); if (!session || sessionTarget.value === session.targetId || !confirm("Start a new session on this target?")) { renderSession(); return; } try { await openNewSession(sessionTarget.value, session.model); } catch (error) { addActivity(session, { kind: "note error", label: "Error", text: error instanceof Error ? error.message : "Target change failed." }); } });
sessionModel.addEventListener("change", async () => { const session = activeSession(); if (!session || sessionModel.value === session.model || !confirm("Start a new session with this model?")) { renderSession(); return; } try { await openNewSession(session.targetId, sessionModel.value); } catch (error) { addActivity(session, { kind: "note error", label: "Error", text: error instanceof Error ? error.message : "Model change failed." }); } });
composer.addEventListener("submit", (event) => { event.preventDefault(); const text = composerInput.value.trim(); if (!text) return; composerInput.value = ""; submit(text); });
composerInput.addEventListener("keydown", (event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); composer.requestSubmit(); } });
pairTarget.onclick = async () => { try { pairingStatus.textContent = "Pairing…"; await jsonFetch("/api/execution-targets/pair", { method: "POST", headers: { "Content-Type": "application/json" }, body: pairingPayload.value }); pairingPayload.value = ""; pairingStatus.textContent = "Target trusted."; await loadTargets(); } catch (error) { pairingStatus.textContent = error instanceof Error ? error.message : "Pairing failed."; } };
identityForm.addEventListener("submit", async (event) => { event.preventDefault(); try { await jsonFetch("/api/identity/allowed", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName: $("#identity-name").value, identity: $("#identity-value").value, publicKey: $("#identity-public-key").value, algorithm: "ed25519" }) }); identityForm.reset(); await renderSettings(); } catch (error) { systemInfo.textContent = error instanceof Error ? error.message : "Identity update failed."; } });

(async () => { if (!await ensureAuth()) return; app.hidden = false; loadPersisted(); await loadTargets(); await loadModels(); await loadSessions(); if (state.activeSessionId) { await activateSession(state.activeSessionId); } else renderSession(); setInterval(async () => { for (const session of state.sessions.values()) { await refreshSession(session); await loadApprovals(session); } renderTabs(); renderAttention(); }, 5000); })().catch((error) => { app.hidden = false; emptyState.hidden = false; emptyState.querySelector("p").textContent = error instanceof Error ? error.message : "Porta could not load."; });
