export function base64urlToUint8Array(value, field = "WebAuthn value") {
  if (typeof value !== "string" || value.length % 4 === 1) throw new Error(`Invalid ${field} encoding`);
  const base64 = value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "=");
  try { const binary = atob(base64); return Uint8Array.from(binary, (character) => character.charCodeAt(0)); } catch { throw new Error(`Invalid ${field} encoding`); }
}
export function uint8ArrayToBase64url(value) { let binary = ""; for (const character of new Uint8Array(value)) binary += String.fromCharCode(character); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
export function registrationOptionsForBrowser(options) { return { ...options, challenge: base64urlToUint8Array(options.challenge, "WebAuthn challenge"), user: { ...options.user, id: base64urlToUint8Array(options.user.id, "WebAuthn user ID") }, ...(options.excludeCredentials ? { excludeCredentials: options.excludeCredentials.map((credential) => ({ ...credential, id: base64urlToUint8Array(credential.id, "WebAuthn credential ID") })) } : {}) }; }
export function loginOptionsForBrowser(options) { return { ...options, challenge: base64urlToUint8Array(options.challenge, "WebAuthn challenge"), ...(options.allowCredentials ? { allowCredentials: options.allowCredentials.map((credential) => ({ ...credential, id: base64urlToUint8Array(credential.id, "WebAuthn credential ID") })) } : {}) }; }
export function credentialToJSON(credential) { const response = credential.response; return { id: credential.id, rawId: uint8ArrayToBase64url(credential.rawId), type: credential.type, response: response.attestationObject ? { clientDataJSON: uint8ArrayToBase64url(response.clientDataJSON), attestationObject: uint8ArrayToBase64url(response.attestationObject), transports: response.getTransports?.() } : { clientDataJSON: uint8ArrayToBase64url(response.clientDataJSON), authenticatorData: uint8ArrayToBase64url(response.authenticatorData), signature: uint8ArrayToBase64url(response.signature), userHandle: response.userHandle ? uint8ArrayToBase64url(response.userHandle) : null } }; }
